"""Workflow deliverable publishing and validation."""

from __future__ import annotations

from pathlib import Path

from ..storage import Blackboard
from .design import DESIGN_PACK_FILES, write_design_pack, write_user_design_document


DESIGN_WORKFLOWS = {"design", "design-lite"}
CODE_WORKFLOWS = {"dev", "dev-lite", "dev-new", "fix", "refactor", "software-dev"}
PLAN_STAGE_IDS = {"plan", "quick_plan", "scaffold_plan", "design_plan", "design_brief", "plan_revise", "design_revise"}
TEST_STAGE_IDS = {"test", "targeted_test", "smoke_check", "run_smoke"}
REVIEW_STAGE_IDS = {
    "review",
    "plan_review",
    "light_review",
    "review_test_result",
    "docs_review",
    "design_review",
    "final_design_review",
    "delivery_verify",
    "docs_verify",
    "plan_verify",
    "design_verify",
}

PLACEHOLDER_DESIGN_TEXT = "This design pack section is generated by muxdev P0"


def publish_workflow_deliverables(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    workspace: Path,
    task: str,
    workflow: str,
    automation: dict[str, object] | None = None,
) -> dict[str, object]:
    """Write idempotent user-facing deliverables and return validation status."""
    workflow = _normalized_workflow(workflow)
    stage_sections = _stage_sections(blackboard, run_id)
    if workflow in DESIGN_WORKFLOWS:
        _publish_design_deliverables(
            blackboard,
            run_dir=run_dir,
            run_id=run_id,
            workspace=workspace,
            task=task,
            workflow=workflow,
            automation=automation or {},
            stage_sections=stage_sections,
        )
    _publish_plan_summary(blackboard, run_dir=run_dir, run_id=run_id, workflow=workflow, stage_sections=stage_sections)
    _publish_test_report(blackboard, run_dir=run_dir, run_id=run_id)
    _publish_review_report(blackboard, run_dir=run_dir, run_id=run_id, stage_sections=stage_sections)
    _publish_handoff_summary(blackboard, run_dir=run_dir, run_id=run_id, task=task, workflow=workflow, stage_sections=stage_sections)
    _publish_docs_report(blackboard, run_dir=run_dir, run_id=run_id, workflow=workflow, stage_sections=stage_sections)
    return workflow_deliverable_status(blackboard, run_dir=run_dir, run_id=run_id, workflow=workflow, require_report=False)


def workflow_deliverable_status(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    workflow: str | None = None,
    require_report: bool = True,
) -> dict[str, object]:
    """Return required/ready/missing deliverables for a workflow run."""
    if workflow is None:
        try:
            workflow = str(blackboard.get_run(run_id).get("workflow") or "")
        except Exception:
            workflow = ""
    workflow = _normalized_workflow(workflow)
    required = _required_deliverables(workflow, require_report=require_report)
    ready = [item for item in required if _deliverable_ready(blackboard, run_dir=run_dir, run_id=run_id, item=item)]
    missing = [item for item in required if item not in ready]
    return {
        "workflow": workflow,
        "required": required,
        "ready": ready,
        "missing": missing,
        "complete": not missing,
    }


def _publish_design_deliverables(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    workspace: Path,
    task: str,
    workflow: str,
    automation: dict[str, object],
    stage_sections: list[tuple[str, str]],
) -> None:
    if not stage_sections:
        raise ValueError("no design stage outputs available")
    manifest = write_design_pack(
        run_dir=run_dir,
        run_id=run_id,
        task=task,
        workflow=workflow,
        automation=automation,
        sections=stage_sections,
    )
    _add_artifact_once(blackboard, run_id, None, "design_contract.json", Path(str(manifest["contract"])), "design_contract")
    _add_artifact_once(blackboard, run_id, None, "memory_proposals.json", Path(str(manifest["memory_proposals"])), "memory_proposals")
    for path in manifest.get("files", []):
        _add_artifact_once(blackboard, run_id, None, Path(str(path)).name, Path(str(path)), "design_pack")

    design_doc = write_user_design_document(
        workspace=workspace,
        run_id=run_id,
        task=task,
        workflow=workflow,
        sections=stage_sections,
    )
    _add_artifact_once(blackboard, run_id, None, "Design Document", design_doc, "project_design_doc")


def _publish_plan_summary(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    workflow: str,
    stage_sections: list[tuple[str, str]],
) -> None:
    plan_sections = [(title, body) for title, body in stage_sections if title in PLAN_STAGE_IDS]
    if not plan_sections:
        return
    lines = ["# Plan Summary", "", f"- Run: {run_id}", f"- Workflow: {workflow}", ""]
    for title, body in plan_sections:
        clean = _clean_section_text(body)
        if not clean:
            continue
        lines.extend([f"## {title}", "", clean, ""])
    path = run_dir / "deliverables" / "plan_summary.md"
    _write_text(path, "\n".join(lines).rstrip() + "\n")
    _add_artifact_once(blackboard, run_id, None, "plan_summary.md", path, "plan_summary")


def _publish_test_report(blackboard: Blackboard, *, run_dir: Path, run_id: str) -> None:
    rows = blackboard.table_rows("test_results", run_id=run_id)
    if not rows:
        return
    lines = ["# Test Report", "", f"- Run: {run_id}", ""]
    for row in rows:
        status = "passed" if bool(row.get("passed")) else "failed"
        lines.append(f"- {row.get('stage_id')}: {status} - {row.get('command')} - {row.get('summary')}")
    path = run_dir / "deliverables" / "test_report.md"
    _write_text(path, "\n".join(lines).rstrip() + "\n")
    _add_artifact_once(blackboard, run_id, None, "test_report.md", path, "test_report")


def _publish_review_report(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    stage_sections: list[tuple[str, str]],
) -> None:
    review_sections = [(title, body) for title, body in stage_sections if title in REVIEW_STAGE_IDS]
    blockers = blackboard.table_rows("review_blockers", run_id=run_id)
    if not review_sections and not blockers:
        return
    lines = ["# Review Report", "", f"- Run: {run_id}", ""]
    if blockers:
        lines.extend(["## Blockers", ""])
        for row in blockers:
            lines.append(f"- {row.get('stage_id')} {row.get('severity')} {row.get('type')}: {row.get('suggestion')}")
        lines.append("")
    else:
        lines.extend(["## Blockers", "", "- none", ""])
    for title, body in review_sections:
        clean = _clean_section_text(body)
        if not clean:
            continue
        lines.extend([f"## {title}", "", clean, ""])
    path = run_dir / "deliverables" / "review_report.md"
    _write_text(path, "\n".join(lines).rstrip() + "\n")
    _add_artifact_once(blackboard, run_id, None, "review_report.md", path, "review_report")


def _publish_handoff_summary(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    task: str,
    workflow: str,
    stage_sections: list[tuple[str, str]],
) -> None:
    if workflow not in {"dev-lite", "dev-new"}:
        return
    handoff = [(title, body) for title, body in stage_sections if title == "handoff_summary"]
    lines = ["# Handoff Summary", "", f"- Run: {run_id}", f"- Workflow: {workflow}", f"- Task: {task}", ""]
    if handoff:
        for title, body in handoff:
            clean = _clean_section_text(body)
            if clean:
                lines.extend([f"## {title}", "", clean, ""])
    else:
        lines.extend(["## Summary", "", "- Implementation completed; review final report and diff for details.", ""])
    path = run_dir / "deliverables" / "handoff_summary.md"
    _write_text(path, "\n".join(lines).rstrip() + "\n")
    _add_artifact_once(blackboard, run_id, None, "handoff_summary.md", path, "handoff_summary")


def _publish_docs_report(
    blackboard: Blackboard,
    *,
    run_dir: Path,
    run_id: str,
    workflow: str,
    stage_sections: list[tuple[str, str]],
) -> None:
    if workflow != "docs":
        return
    docs_sections = [(title, body) for title, body in stage_sections if title in {"docs_update", "docs_fix"}]
    if not docs_sections:
        return
    lines = ["# Docs Update Report", "", f"- Run: {run_id}", ""]
    for title, body in docs_sections:
        clean = _clean_section_text(body)
        if clean:
            lines.extend([f"## {title}", "", clean, ""])
    path = run_dir / "deliverables" / "docs_report.md"
    _write_text(path, "\n".join(lines).rstrip() + "\n")
    _add_artifact_once(blackboard, run_id, None, "docs_report.md", path, "docs_report")


def _required_deliverables(workflow: str, *, require_report: bool) -> list[str]:
    required: list[str]
    if workflow in DESIGN_WORKFLOWS:
        required = ["project_design_doc", "design_pack"]
    elif workflow in CODE_WORKFLOWS:
        required = ["diff_nonempty", "test_report", "review_report"]
        if workflow in {"dev-lite", "dev-new"}:
            required.append("handoff_summary")
    elif workflow == "test":
        required = ["plan_summary", "test_report", "review_report"]
    elif workflow == "review":
        required = ["review_report"]
    elif workflow == "docs":
        required = ["diff_nonempty", "docs_report", "review_report"]
    else:
        required = []
    if require_report:
        required.append("report")
    return required


def _deliverable_ready(blackboard: Blackboard, *, run_dir: Path, run_id: str, item: str) -> bool:
    if item == "diff_nonempty":
        path = _artifact_path(blackboard, run_id, "diff") or run_dir / "diff.patch"
        return path.exists() and path.is_file() and path.stat().st_size > 0
    if item == "report":
        path = _artifact_path(blackboard, run_id, "report") or run_dir / "final_report.md"
        return path.exists() and path.is_file() and path.stat().st_size > 0
    if item == "design_pack":
        design_dir = run_dir / "design"
        return all(_design_pack_file_ready(design_dir / filename) for filename in DESIGN_PACK_FILES)
    path = _artifact_path(blackboard, run_id, item)
    return bool(path and path.exists() and path.is_file() and path.stat().st_size > 0)


def _design_pack_file_ready(path: Path) -> bool:
    if not path.exists() or not path.is_file() or path.stat().st_size == 0:
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    return PLACEHOLDER_DESIGN_TEXT not in text


def _artifact_path(blackboard: Blackboard, run_id: str, kind: str) -> Path | None:
    for row in reversed(blackboard.table_rows("artifacts", run_id=run_id)):
        if str(row.get("kind") or "") != kind:
            continue
        path = Path(str(row.get("path") or ""))
        if path:
            return path
    return None


def _stage_sections(blackboard: Blackboard, run_id: str) -> list[tuple[str, str]]:
    sections: list[tuple[str, str]] = []
    for row in blackboard.table_rows("artifacts", run_id=run_id):
        if row.get("kind") != "stage_output":
            continue
        path = Path(str(row.get("path") or ""))
        if not path.exists() or not path.is_file():
            continue
        title = str(row.get("stage_id") or path.stem)
        sections.append((title, path.read_text(encoding="utf-8", errors="replace")))
    return sections


def _add_artifact_once(
    blackboard: Blackboard,
    run_id: str,
    stage_id: str | None,
    name: str,
    path: Path,
    kind: str,
) -> None:
    resolved = str(path)
    for row in blackboard.table_rows("artifacts", run_id=run_id):
        if str(row.get("kind") or "") == kind and str(row.get("path") or "") == resolved:
            return
    blackboard.add_artifact(run_id, stage_id, name, path, kind)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _clean_section_text(text: str) -> str:
    clean = str(text).strip()
    if "\n# Stream Events\n" in clean:
        clean = clean.split("\n# Stream Events\n", 1)[0].strip()
    if "\n# Session Archives\n" in clean:
        clean = clean.split("\n# Session Archives\n", 1)[0].strip()
    return clean


def _normalized_workflow(workflow: str) -> str:
    value = str(workflow or "")
    if value == "design-v2":
        return "design"
    if value == "dev-light":
        return "dev-lite"
    return value
