"""Design pack writer for the first-class ``muxdev design`` flow."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..models import utc_now


DESIGN_PACK_FILES = [
    "00_problem_statement.md",
    "01_requirements.md",
    "02_architecture_options.md",
    "03_decision_record.md",
    "04_system_design.md",
    "05_api_and_data_model.md",
    "06_risk_and_threat_model.md",
    "07_test_strategy.md",
    "08_implementation_roadmap.md",
    "09_open_questions.md",
    "10_final_design_review.md",
]


def write_design_pack(
    *,
    run_dir: Path,
    run_id: str,
    task: str,
    workflow: str,
    automation: dict[str, Any] | None = None,
) -> dict[str, object]:
    """Create the design pack files and return an artifact manifest."""
    design_dir = run_dir / "design"
    design_dir.mkdir(parents=True, exist_ok=True)
    automation = automation or {}
    for filename in DESIGN_PACK_FILES:
        path = design_dir / filename
        if not path.exists():
            path.write_text(_markdown_for(filename, task, run_id, automation), encoding="utf-8")

    contract = {
        "contract_version": "muxdev.design_contract.v1",
        "run_id": run_id,
        "workflow": workflow,
        "task": task,
        "created_at": utc_now(),
        "intent": automation.get("intent", "design"),
        "depth": automation.get("depth", "deep"),
        "topology": automation.get("topology", "squad"),
        "roles": automation.get("roles", []),
        "artifacts": DESIGN_PACK_FILES,
        "memory_proposals": "memory_proposals.json",
    }
    contract_path = design_dir / "design_contract.json"
    contract_path.write_text(json.dumps(contract, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    proposals = [
        {
            "kind": "architecture_decision",
            "claim": f"Design run {run_id} produced an implementation contract for: {task}",
            "source_evidence": str(contract_path),
            "status": "proposed",
            "confidence": 0.7,
        }
    ]
    proposals_path = design_dir / "memory_proposals.json"
    proposals_path.write_text(json.dumps(proposals, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    return {
        "design_dir": str(design_dir),
        "contract": str(contract_path),
        "memory_proposals": str(proposals_path),
        "files": [str(design_dir / filename) for filename in DESIGN_PACK_FILES],
    }


def latest_design_contract(workspace: Path) -> Path | None:
    """Find the newest local design contract under the workspace runtime root."""
    candidates = sorted((workspace / ".muxdev" / "runs").glob("*/design/design_contract.json"))
    return candidates[-1] if candidates else None


def _markdown_for(filename: str, task: str, run_id: str, automation: dict[str, Any]) -> str:
    title = filename[3:-3].replace("_", " ").title()
    roles = ", ".join(str(role) for role in automation.get("roles", []) or []) or "design roles"
    return "\n".join(
        [
            f"# {title}",
            "",
            f"- Run: {run_id}",
            f"- Task: {task}",
            f"- Roles: {roles}",
            "",
            "This design pack section is generated by muxdev P0 and is ready for role output consolidation.",
            "",
        ]
    )
