"""Provider discovery and runtime-adapter public API."""

from .adapters import HeadlessCliProviderAdapter, MockProviderAdapter, ProviderAdapter, ProviderStageOutput, get_runtime_provider
from .certified import CodexHarnessAdapter, QwenHarnessAdapter, ReplayAdapter, decode_codex_jsonl, decode_qwen_stream_json
from .contracts import (
    ProviderActionDecision,
    ProviderCapabilities,
    ProviderDescriptor,
    ProviderResumeResult,
    ProviderRuntime,
    ProviderRuntimeKind,
    ProviderSession,
    ProviderStreamEvent,
)
from .harness import (
    ADAPTER_CONTRACT_VERSION,
    STANDARD_CAPABILITIES,
    AdapterProbe,
    AgentHarnessAdapter,
    AttemptHandle,
    CancelResult,
    CapabilityVerificationState,
    CertificationReport,
    CertificationStatus,
    HarnessEvent,
    HarnessEventSource,
    IsolationMode,
    TrustTier,
    Unsupported,
)
from .planner import ProviderPlanner, ProviderRouteDecision
from .registry import (
    CapabilityState,
    CommandResult,
    ProviderDefinition,
    ProviderProbe,
    ProviderStatus,
    detect_providers,
    get_provider_definition,
    probe_provider,
)

__all__ = [
    "CapabilityState",
    "CapabilityVerificationState",
    "CertificationReport",
    "CertificationStatus",
    "CodexHarnessAdapter",
    "CommandResult",
    "HeadlessCliProviderAdapter",
    "HarnessEvent",
    "HarnessEventSource",
    "AgentHarnessAdapter",
    "AdapterProbe",
    "AttemptHandle",
    "CancelResult",
    "ADAPTER_CONTRACT_VERSION",
    "STANDARD_CAPABILITIES",
    "IsolationMode",
    "MockProviderAdapter",
    "ProviderActionDecision",
    "ProviderAdapter",
    "ProviderCapabilities",
    "ProviderDefinition",
    "ProviderDescriptor",
    "ProviderProbe",
    "ProviderPlanner",
    "ProviderResumeResult",
    "ProviderRouteDecision",
    "ProviderRuntime",
    "ProviderRuntimeKind",
    "ProviderSession",
    "ProviderStageOutput",
    "ProviderStatus",
    "ProviderStreamEvent",
    "QwenHarnessAdapter",
    "ReplayAdapter",
    "TrustTier",
    "Unsupported",
    "decode_codex_jsonl",
    "decode_qwen_stream_json",
    "detect_providers",
    "get_provider_definition",
    "get_runtime_provider",
    "probe_provider",
]
