"""Conversation-first dashboard HTML kept separate from the HTTP adapter."""


def conversation_dashboard_html() -> str:
    return r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" href="data:,">
<title>MuxDev Conversation</title>
<style>
:root{color-scheme:light;--ink:#17202a;--muted:#667085;--line:#e4e7ec;--panel:#f7f9fc;--surface:#fff;--brand:#175cd3;--brand-soft:#eff8ff;--pass:#067647;--pass-soft:#ecfdf3;--warn:#b54708;--warn-soft:#fffaeb;--danger:#b42318;--danger-soft:#fef3f2;--shadow:0 1px 3px rgba(16,24,40,.08)}
*{box-sizing:border-box}html,body{height:100%;margin:0}body{font:14px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:var(--panel)}button,textarea,select,input{font:inherit}button{cursor:pointer}.app{display:grid;grid-template-columns:290px minmax(420px,1fr) 340px;height:100vh;overflow:hidden}.rail,.trust{background:var(--surface);min-width:0}.rail{border-right:1px solid var(--line);display:flex;flex-direction:column}.trust{border-left:1px solid var(--line);overflow:auto}.brand{padding:20px;border-bottom:1px solid var(--line)}.brand h1{font-size:20px;margin:0}.brand p{color:var(--muted);margin:3px 0 0;font-size:12px}.new-button,.primary,.secondary,.quiet{border-radius:8px;padding:9px 12px;font-weight:700}.new-button,.primary{border:0;background:var(--brand);color:#fff}.new-button{width:100%;margin-top:14px}.secondary{border:1px solid var(--line);background:#fff;color:#344054}.quiet{border:0;background:transparent;color:var(--brand);padding:5px}.filters{display:flex;gap:6px;padding:12px 14px;border-bottom:1px solid var(--line);overflow:auto}.filter{white-space:nowrap;border:0;border-radius:999px;padding:5px 9px;background:var(--panel);color:var(--muted)}.filter.active{background:var(--brand-soft);color:var(--brand);font-weight:700}.conversations{overflow:auto;padding:8px}.conversation-item{display:block;width:100%;border:0;border-radius:10px;background:transparent;text-align:left;padding:11px;margin-bottom:3px;color:inherit}.conversation-item:hover,.conversation-item.active{background:var(--panel)}.conversation-title{font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.conversation-meta{display:flex;justify-content:space-between;gap:8px;color:var(--muted);font-size:12px;margin-top:4px}.status{font-weight:700}.status.awaiting_acceptance,.status.delivered{color:var(--pass)}.status.needs_user{color:var(--danger)}.status.verifying,.status.recovering,.status.working{color:var(--warn)}
.room{display:flex;min-width:0;flex-direction:column;background:#fff}.room-header{min-height:72px;padding:14px 20px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:16px}.room-title{font-size:17px;font-weight:800}.room-subtitle{color:var(--muted);font-size:12px;margin-top:3px}.room-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.timeline{flex:1;overflow:auto;padding:22px max(20px,6vw);background:linear-gradient(#fff,#fbfcfe)}.empty{height:100%;display:grid;place-items:center;color:var(--muted);text-align:center}.empty strong{display:block;color:var(--ink);font-size:20px;margin-bottom:6px}.event{max-width:760px;margin:0 auto 14px}.message{display:flex;gap:10px}.actor{width:34px;height:34px;border-radius:9px;background:var(--brand-soft);color:var(--brand);display:grid;place-items:center;font-weight:800;flex:0 0 auto}.message-body{min-width:0;flex:1}.message-head{font-size:12px;color:var(--muted);margin-bottom:4px}.bubble{display:inline-block;max-width:100%;padding:10px 12px;border-radius:4px 12px 12px 12px;background:var(--panel);white-space:pre-wrap;overflow-wrap:anywhere}.event.developer .message{flex-direction:row-reverse}.event.developer .message-head{text-align:right}.event.developer .bubble{float:right;background:var(--brand);color:#fff;border-radius:12px 4px 12px 12px}.card{border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:var(--shadow);padding:14px 16px}.card.pass{border-left:4px solid var(--pass)}.card.warn{border-left:4px solid var(--warn)}.card.danger{border-left:4px solid var(--danger)}.eyebrow{text-transform:uppercase;letter-spacing:.07em;font-weight:800;font-size:10px;color:var(--muted)}.card-title{font-weight:800;margin-top:4px}.card-copy{color:#475467;margin-top:5px;white-space:pre-wrap}.composer{border-top:1px solid var(--line);padding:12px 18px;background:#fff}.composer-box{max-width:850px;margin:auto;border:1px solid #d0d5dd;border-radius:12px;padding:10px;box-shadow:0 1px 2px rgba(16,24,40,.04)}textarea{width:100%;min-height:58px;max-height:180px;resize:vertical;border:0;outline:0;padding:4px;background:transparent}.composer-tools{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:7px}.composer-tools select{border:1px solid var(--line);border-radius:7px;padding:6px;color:#475467;background:#fff}.hint{font-size:12px;color:var(--muted)}
.progress-wrap{width:min(420px,52vw);margin-top:7px}.progress-meta{display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:11px}.progress-track{height:7px;border-radius:999px;background:#eaecf0;overflow:hidden;margin-top:4px}.progress-bar{height:100%;width:0;background:var(--brand);transition:width .3s ease}.progress-bar.waiting_user{background:var(--warn)}.progress-bar.failed{background:var(--danger)}.progress-bar.completed{background:var(--pass)}.question-options{display:grid;gap:7px;margin-top:12px}.question-option{text-align:left;border:1px solid var(--line);border-radius:9px;background:#fff;padding:9px}.question-option.recommended{border-color:var(--brand);background:var(--brand-soft)}.question-option small{display:block;color:var(--muted);font-weight:400}.question-custom{display:flex;gap:7px;margin-top:9px}.question-custom input{flex:1;min-width:0;border:1px solid var(--line);border-radius:8px;padding:8px}.countdown{font-size:12px;color:var(--warn);margin-top:8px}.stage-delivery{border:1px solid var(--line);border-radius:10px;padding:11px;margin-top:9px}.stage-delivery header{display:flex;justify-content:space-between;gap:8px}.stage-delivery h3{font-size:13px;margin:0}.stage-block{margin-top:9px}.stage-block strong{font-size:11px;color:var(--muted)}.stage-block ul{margin:5px 0 0;padding-left:18px}.stage-output{white-space:pre-wrap;max-height:150px;overflow:auto;font-size:12px;color:#475467}.standard-editor{margin-top:8px}.standard-editor textarea{border:1px solid var(--line);border-radius:8px;min-height:80px}.standard-editor .recovery-actions{justify-content:flex-end}
.trust-section{padding:18px;border-bottom:1px solid var(--line)}.trust-section h2{font-size:13px;margin:0 0 12px}.kv{display:grid;grid-template-columns:100px 1fr;gap:8px;font-size:12px;margin-bottom:8px}.kv dt{color:var(--muted)}.kv dd{margin:0;overflow-wrap:anywhere}.contract{padding:12px;border-radius:10px;background:var(--panel)}.contract h3{font-size:14px;margin:0 0 6px}.contract p{margin:0;color:#475467}.criteria{padding-left:18px;margin:8px 0 0}.delivery,.team-member{border:1px solid var(--line);border-radius:9px;padding:10px;margin-top:8px}.delivery strong,.team-member strong{display:block}.delivery small,.team-member small{display:block;color:var(--muted);overflow-wrap:anywhere}.team-member.active{border-color:var(--warn);background:var(--warn-soft)}.team-member.failed{border-color:var(--danger)}.team-member.completed{border-color:#abefc6}.failure-meta{display:flex;gap:8px;flex-wrap:wrap;color:var(--muted);font-size:12px;margin-top:7px}.failure-details{margin:8px 0 0;padding-left:18px;color:#475467}.recovery-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.recovery-attempt{font-size:12px;color:#475467;margin-top:5px}.command{font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;background:var(--panel);padding:7px;border-radius:7px;margin-top:7px;overflow-wrap:anywhere}.notice{position:fixed;left:50%;top:16px;transform:translateX(-50%);z-index:10;background:#101828;color:#fff;padding:9px 14px;border-radius:8px;box-shadow:var(--shadow)}.notice.error{background:var(--danger)}.new-panel{padding:14px;border-bottom:1px solid var(--line);background:var(--panel)}.new-panel input,.new-panel textarea,.new-panel select{width:100%;border:1px solid var(--line);border-radius:8px;background:#fff;padding:8px;margin-bottom:8px}.new-panel textarea{min-height:84px}.new-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pairing{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:rgba(16,24,40,.48);padding:20px}.pairing-card{width:min(420px,100%);background:#fff;border-radius:16px;padding:24px;box-shadow:0 18px 48px rgba(16,24,40,.22)}.pairing-card h2{margin:0 0 6px}.pairing-card p{color:var(--muted);margin:0 0 16px}.pairing-card input{width:100%;border:1px solid var(--line);border-radius:8px;padding:10px;margin-bottom:10px}.pairing-card button{width:100%}.hidden{display:none!important}
@media(max-width:1050px){.app{grid-template-columns:250px 1fr}.trust{display:none}}@media(max-width:720px){.app{display:block;height:auto;min-height:100vh}.rail{height:auto;border-right:0}.conversations{display:flex;overflow:auto}.conversation-item{min-width:220px}.room{min-height:calc(100vh - 210px)}.trust{display:block;border-left:0;border-top:1px solid var(--line)}.room-header{display:block}.room-actions{justify-content:flex-start;margin-top:10px}.room-actions button{max-width:100%;white-space:normal}.timeline{padding:18px 12px}.message-body{min-width:0}.bubble{max-width:calc(100vw - 74px);overflow-wrap:anywhere}.hint{display:none}}
</style>
</head>
<body>
<div id="notice" class="notice hidden" role="status"></div>
<section id="pairing" class="pairing hidden"><form id="pair-form" class="pairing-card"><h2>连接这台开发机器</h2><p>输入本地 MuxDev 终端显示的一次性配对码。每台浏览器会获得独立、可撤销的设备身份。</p><input id="device-label" value="我的浏览器" required aria-label="设备名称"><input id="pair-code" required autocomplete="one-time-code" aria-label="一次性配对码" placeholder="一次性配对码"><button class="primary" type="submit">安全连接</button></form></section>
<main class="app">
  <aside class="rail">
    <div class="brand"><h1>MuxDev Conversation</h1><p>一个会话，完成一次可信开发交付</p><button id="new-toggle" class="new-button" type="button">新建任务会话</button></div>
    <form id="new-form" class="new-panel hidden">
      <input id="new-title" aria-label="会话名称" placeholder="会话名称（可选）">
      <textarea id="new-goal" required aria-label="任务目标" placeholder="描述需要完成的开发任务"></textarea>
      <div class="new-grid"><select id="new-profile" aria-label="交付级别"><option value="lite">Lite</option><option value="standard">Standard</option><option value="strict">Strict</option></select><select id="new-provider" aria-label="主要实现 Agent"><option value="mock">mock · 流程演示</option></select></div>
      <p class="hint">这里选择主要实现 Agent；系统会自动建立规划、实现、测试和评审团队。真实开发请选择已就绪 Provider；mock 只验证流程。Standard/Strict 需要独立 Reviewer。</p>
      <button class="primary" type="submit">创建并开始</button>
      <button id="new-cancel" class="quiet" type="button">取消</button>
    </form>
    <div class="filters"><button class="filter active" data-filter="" type="button">全部</button><button class="filter" data-filter="needs_user" type="button">需要你处理</button><button class="filter" data-filter="awaiting_acceptance" type="button">待接受</button></div>
    <nav id="conversations" class="conversations" aria-label="任务会话"></nav>
  </aside>
  <section class="room">
    <header class="room-header"><div><div id="room-title" class="room-title">选择一个任务会话</div><div id="room-subtitle" class="room-subtitle">持续沟通、自动修复并完成可信交付</div><div id="room-progress" class="progress-wrap hidden"><div class="progress-meta"><span id="progress-label"></span><span id="progress-value"></span></div><div class="progress-track" role="progressbar" aria-label="可信交付阶段进度" aria-valuemin="0" aria-valuemax="100"><div id="progress-bar" class="progress-bar"></div></div></div></div><div id="room-actions" class="room-actions"></div></header>
    <div id="timeline" class="timeline" aria-live="polite" aria-label="会话执行时间线"><div class="empty"><div><strong>让开发任务在一个会话中走完</strong>创建会话后，需求、执行、自愈、验证与交付都会保留在这里。</div></div></div>
    <form id="composer" class="composer hidden"><div class="composer-box"><textarea id="message" required aria-label="发送消息" placeholder="继续补充任务、回答问题或讨论交付结果"></textarea><div class="composer-tools"><div><select id="intent" aria-label="消息用途"><option value="change">要求修改</option><option value="discuss">仅讨论</option><option value="answer">回答问题</option><option value="verify">要求验证</option></select><span class="hint">仅讨论不会使已验证交付失效</span></div><button class="primary" type="submit">发送</button></div></div></form>
  </section>
  <aside id="trust" class="trust"><div class="trust-section"><h2>可信交付</h2><p class="hint">选择会话后查看契约、候选版本和 Evidence。</p></div></aside>
</main>
<script>
const state={conversations:[],selected:null,detail:null,filter:"",source:null,timelineRequest:0};
const labels={clarifying:"澄清中",working:"工作中",needs_user:"需要你处理",candidate_ready:"候选就绪",verifying:"验证中",recovering:"自愈中",awaiting_acceptance:"等待接受",delivered:"已交付",closed:"已关闭",pending:"等待中",running:"执行中",waiting_user:"等待确认",completed:"已完成",skipped:"已跳过",verified:"已验证",accepted:"已接受",failed:"未通过",invalidated:"已失效"};
function el(tag,text,className){const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=text;return item}
function showNotice(text,error=false){const item=document.querySelector("#notice");item.textContent=text;item.className=`notice${error?" error":""}`;setTimeout(()=>item.classList.add("hidden"),3500)}
async function api(url,options){const response=await fetch(url,options);if(response.status===401){document.querySelector("#pairing").classList.remove("hidden");throw new Error("需要先配对这台设备")}if(!response.ok){let message=`HTTP ${response.status}`;try{const payload=await response.json();message=payload.detail||message}catch(parseError){message=`${message} · ${String(parseError)}`}throw new Error(message)}return response.json()}
function formatTime(value){if(!value)return "";try{return new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}catch{return value}}
async function loadConversations(){const query=state.filter?`?status=${encodeURIComponent(state.filter)}`:"";state.conversations=await api(`/api/v1/conversations${query}`);renderConversations();if(!state.selected&&state.conversations.length)await selectConversation(state.conversations[0].conversation_id)}
async function loadProviders(){const select=document.querySelector("#new-provider");try{const providers=await api("/providers"),usable=providers.filter(item=>["ready","partial"].includes(item.status));select.replaceChildren();for(const item of usable){const option=el("option",`${item.provider} · ${item.status}`);option.value=item.provider;select.appendChild(option)}if(!usable.length){const option=el("option","mock · 流程演示");option.value="mock";select.appendChild(option)}const preferred=usable.find(item=>item.provider!=="mock"&&item.status==="ready")||usable.find(item=>item.provider!=="mock");select.value=preferred?.provider||"mock"}catch{select.value="mock"}}
function renderConversations(){const root=document.querySelector("#conversations");root.replaceChildren();for(const item of state.conversations){const button=el("button",undefined,`conversation-item${item.conversation_id===state.selected?" active":""}`);button.type="button";button.addEventListener("click",()=>selectConversation(item.conversation_id));const title=el("div",item.title,"conversation-title"),meta=el("div",undefined,"conversation-meta"),status=el("span",labels[item.status]||item.status,`status ${item.status}`),time=el("span",formatTime(item.updated_at));meta.append(status,time);button.append(title,meta);root.appendChild(button)}if(!state.conversations.length)root.appendChild(el("div","还没有符合条件的会话。","hint"))}
async function selectConversation(id){state.selected=id;renderConversations();if(state.source)state.source.close();await refreshDetail();state.source=new EventSource(`/api/v1/conversations/${encodeURIComponent(id)}/events`);state.source.onopen=()=>refreshDetail();state.source.addEventListener("conversation",()=>refreshDetail());state.source.onerror=()=>{} }
async function refreshDetail(){if(!state.selected)return;state.detail=await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}`);renderDetail();await loadConversations()}
function renderDetail(){const detail=state.detail,conversation=detail.conversation;document.querySelector("#room-title").textContent=conversation.title;document.querySelector("#room-subtitle").textContent=`${labels[conversation.status]||conversation.status} · ${conversation.conversation_id}`;document.querySelector("#composer").classList.toggle("hidden",conversation.status==="closed");renderProgress(detail.progress);renderActions(conversation,detail.candidates,detail.recovery,detail.interactions||[]);renderTimeline();renderTrust()}
function renderProgress(progress){const root=document.querySelector("#room-progress"),bar=document.querySelector("#progress-bar"),track=root.querySelector(".progress-track");root.classList.remove("hidden");const value=progress?.percent||0;document.querySelector("#progress-label").textContent=progress?.label||"等待开始";document.querySelector("#progress-value").textContent=`${value}% · ${progress?.completed_stages||0}/${progress?.total_stages||0} 阶段`;bar.style.width=`${value}%`;bar.className=`progress-bar ${progress?.state||"pending"}`;track.setAttribute("aria-valuenow",String(value));track.setAttribute("aria-valuetext",`${progress?.label||"等待开始"}，${value}%`)}
function renderActions(conversation,candidates,recovery,interactions){const root=document.querySelector("#room-actions");root.replaceChildren();const active=candidates.find(item=>item.candidate_id===conversation.active_candidate_id),hasQuestion=interactions.some(item=>item.status==="pending");if(conversation.status==="needs_user"&&!hasQuestion)appendRecoveryActions(root,recovery?.next_actions||[],true);if(conversation.status==="awaiting_acceptance"&&active)root.append(action("接受可信交付",()=>acceptDelivery(active.candidate_id),"primary"),action("继续修改",()=>sendAction("continue_revision"),"secondary"));if(conversation.status==="delivered")root.append(action("继续修订",()=>sendAction("continue_revision"),"secondary"),action("关闭会话",()=>sendAction("close"),"secondary"));if(conversation.status==="closed")root.append(action("重新打开",()=>sendAction("reopen"),"secondary"));if(["clarifying","working"].includes(conversation.status))root.append(action("开始验证",()=>sendAction("verify"),"primary"))}
function action(text,handler,className){const button=el("button",text,className);button.type="button";button.addEventListener("click",handler);return button}
function appendRecoveryActions(root,items,compact=false){for(const item of items){const recoverable=["auto","fix-output","retry","switch-provider"].includes(item.action),restart=item.action==="start_work",label=item.label||item.action;if(recoverable||restart){const button=action(label,()=>restart?sendAction("start_work"):sendAction("auto_recover",{recovery_action:item.action}),compact?"primary":"secondary");button.setAttribute("aria-label",`${label}：${item.description||"执行恢复动作"}`);root.appendChild(button)}else if(item.command){const button=action(label,()=>copyCommand(item.command),"secondary");button.setAttribute("aria-label",`${label}：复制命令 ${item.command}`);root.appendChild(button)}}}
async function copyCommand(command){try{await navigator.clipboard.writeText(command);showNotice("诊断命令已复制")}catch{showNotice(`请手动执行：${command}`,true)}}
function renderTimeline(){const root=document.querySelector("#timeline"),requestId=++state.timelineRequest;api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/events`).then(events=>{if(requestId!==state.timelineRequest)return;root.replaceChildren();let previous="";for(const event of events){if(!visibleEvent(event))continue;const key=eventKey(event);if(key===previous)continue;previous=key;root.appendChild(renderEvent(event))}root.scrollTop=root.scrollHeight}).catch(error=>showNotice(error.message,true))}
function visibleEvent(event){if(event.type!=="run.event")return true;const payload=event.payload||{},source=payload.source_type||"";if(source==="run.status_changed")return ["running","blocked","awaiting_approval"].includes(payload.summary);return ["run.initializing","team.resolved","worker.started","worker.completed","worker.failed","worker.waiting","supervisor.fanout.started","supervisor.fanout.completed","recovery.requested","recovery.started","recovery.finished","interaction.requested","interaction.responded","interaction.resume"].includes(source)}
function eventKey(event){const payload=event.payload||{};return `${event.type}:${payload.source_type||""}:${payload.stage_id||""}:${payload.attempt||""}:${payload.status||""}:${payload.summary||""}`}
function renderEvent(event){const wrapper=el("article",undefined,`event ${event.actor}`),payload=event.payload||{};if(event.type==="user.message"||event.type.endsWith(".message")){const row=el("div",undefined,"message"),actor=el("div",event.actor==="developer"?"你":event.actor==="reviewer"?"评":event.actor==="implementer"?"实":"M","actor"),body=el("div",undefined,"message-body"),head=el("div",`${actorLabel(event.actor)} · ${formatTime(event.created_at)}`,"message-head"),bubble=el("div",payload.content||payload.summary||event.type,"bubble");body.append(head,bubble);row.append(actor,body);wrapper.appendChild(row);return wrapper}let tone="";if(event.type==="delivery.verified"||event.type==="delivery.accepted"||payload.source_type==="worker.completed")tone=" pass";else if(event.type.includes("failed")||event.type.includes("needs_user")||event.type.includes("invalidated")||event.type==="run.orphaned"||payload.source_type==="worker.failed")tone=" danger";else if(event.type.startsWith("run.")||event.type.includes("recover")||event.type.startsWith("interaction.")||payload.source_type==="worker.waiting"||payload.source_type==="interaction.requested")tone=" warn";const card=el("div",undefined,`card${tone}`);card.append(el("div",eventLabel(event),"eyebrow"),el("div",runEventTitle(payload)||summaryLabel(payload.summary||payload.message)||eventTitle(event.type),"card-title"));if(payload.source_type==="interaction.requested")renderInteraction(card,payload);else if(event.type==="delivery.needs_user"||event.type==="run.failed_to_start"||event.type==="recovery.failed"||event.type==="run.orphaned")renderFailure(card,payload);else if(event.type==="contract.revised"&&(payload.affected_stages||[]).length)card.appendChild(el("div",`需重新验证：${payload.affected_stages.join("、")}`,"card-copy"));else if(payload.next_action)card.appendChild(el("div",payload.next_action,"card-copy"));wrapper.appendChild(card);return wrapper}
function runEventTitle(payload){const source=payload.source_type||"";if(source==="run.initializing")return "Run 已建立，正在预检 Agent 团队";if(source==="team.resolved")return `Agent 团队已就绪 · 最多并行 ${payload.max_parallel||4}`;if(source==="worker.started")return `${payload.role||"Agent"} · ${payload.provider||"待分配"} 开始 ${payload.stage_id||"阶段"}`;if(source==="worker.completed")return `${payload.role||"Agent"} · ${payload.provider||"待分配"} 已完成 ${payload.stage_id||"阶段"}`;if(source==="worker.waiting")return `${payload.role||"Agent"} 正在等待你的选择`;if(source==="worker.failed")return `${payload.role||"Agent"} · ${payload.provider||"待分配"} 执行失败`;if(source==="interaction.requested")return payload.question||"Agent 需要确认一项需求";if(source==="interaction.responded")return payload.defaulted?"1 分钟未回复，已采用推荐项":"问题已回答，准备继续执行";if(source==="interaction.resume")return "已根据你的回答继续当前阶段";if(source==="supervisor.fanout.started")return `并行执行：${(payload.stages||[]).join("、")}`;if(source==="supervisor.fanout.completed")return `并行阶段已按固定顺序合并`;return ""}
function renderInteraction(card,payload){const interaction=(state.detail.interactions||[]).find(item=>item.interaction_id===payload.interaction_id)||payload,pending=interaction.status==="pending"||!interaction.status;if(interaction.reason)card.appendChild(el("div",interaction.reason,"card-copy"));const meta=el("div",undefined,"failure-meta");meta.append(el("span",interaction.blocking?"必须人工确认":"低风险澄清"),el("span",`阶段 ${interaction.stage_id||payload.stage_id||"当前"}`));card.appendChild(meta);if(!pending){card.appendChild(el("div",interaction.status==="approved"?"已批准":interaction.status==="rejected"?"已拒绝":"已回答","card-copy"));return}const options=el("div",undefined,"question-options");for(const item of interaction.options||[]){const button=el("button",undefined,`question-option${item.id===interaction.recommended_option_id?" recommended":""}`);button.type="button";button.appendChild(el("strong",`${item.label}${item.id===interaction.recommended_option_id?"（推荐）":""}`));if(item.description)button.appendChild(el("small",item.description));button.addEventListener("click",()=>answerInteraction(interaction.interaction_id,item.id));options.appendChild(button)}card.appendChild(options);if(interaction.allow_custom_input!==false){const form=el("form",undefined,"question-custom"),input=el("input"),send=el("button","提交说明","secondary");input.placeholder="也可以自行输入";input.setAttribute("aria-label","自定义回答");send.type="submit";form.addEventListener("submit",event=>{event.preventDefault();if(input.value.trim())answerInteraction(interaction.interaction_id,null,input.value.trim())});form.append(input,send);card.appendChild(form)}const countdown=el("div",undefined,"countdown");if(interaction.blocking)countdown.textContent="此问题不会超时自动选择，收到明确确认前执行保持暂停。";else if(interaction.expires_at){const seconds=Math.max(0,Math.ceil((new Date(interaction.expires_at)-Date.now())/1000));countdown.textContent=`${seconds} 秒后未回复将采用推荐项。`}card.appendChild(countdown)}
async function answerInteraction(interactionId,optionId,customInput){try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"respond_interaction",payload:{interaction_id:interactionId,option_id:optionId||null,custom_input:customInput||null},idempotency_key:crypto.randomUUID()})});showNotice("回答已提交，Agent 将从当前阶段继续");setTimeout(refreshDetail,500)}catch(error){showNotice(error.message,true)}}
function renderFailure(card,payload){const failure=payload.failure||{},recovery=payload.recovery||{};const meta=el("div",undefined,"failure-meta");for(const text of [failure.stage_id&&`阶段 ${failure.stage_id}`,failure.provider&&`Agent ${failure.provider}`,failure.returncode!==undefined&&failure.returncode!==null&&`退出码 ${failure.returncode}`,failure.code&&`原因 ${failure.code}`].filter(Boolean))meta.appendChild(el("span",text));if(meta.childNodes.length)card.appendChild(meta);if(failure.summary)card.appendChild(el("div",failure.summary,"card-copy"));if((failure.details||[]).length){const details=el("ul",undefined,"failure-details");for(const text of failure.details)details.appendChild(el("li",text));card.appendChild(details)}for(const item of recovery.attempts||[])card.appendChild(el("div",`${item.action} · ${item.provider||"当前 Agent"} · ${item.status}`,"recovery-attempt"));if(recovery.workspace_message)card.appendChild(el("div",recovery.workspace_message,"card-copy"));const controls=el("div",undefined,"recovery-actions");appendRecoveryActions(controls,payload.next_actions||[],false);if(controls.childNodes.length)card.appendChild(controls);if(payload.candidate_id){const link=el("a","查看 Evidence");link.href=`/api/v1/deliveries/${encodeURIComponent(payload.candidate_id)}/evidence`;link.target="_blank";link.rel="noopener";link.setAttribute("aria-label","查看本次失败的 Evidence");card.appendChild(link)}}
function actorLabel(actor){return {developer:"开发者",implementer:"实施者",reviewer:"独立评审",supervisor:"MuxDev"}[actor]||actor}
function eventLabel(event){if(event.type==="run.event")return "执行状态";return {"contract.created":"交付契约","contract.revised":"契约修订","run.requested":"执行周期","delivery.verified":"可信候选","delivery.accepted":"已接受交付","delivery.invalidated":"候选失效"}[event.type]||event.type.replaceAll("."," · ")}
function summaryLabel(value){return {running:"正在执行并收集运行时事实",blocked:"当前执行需要处理",awaiting_approval:"正在等待你的确认"}[value]||value}
function eventTitle(type){const titles={"contract.created":"交付契约已建立","contract.revised":"交付契约已修订","workspace.prepared":"隔离工作树已准备","run.requested":"已开始新的执行周期","run.orphaned":"后台执行已中断，可重新建立 Run","run.event":"Run 事实已更新","interaction.awaiting_user":"执行已安全暂停，等待你的选择","interaction.answer_received":"已收到你的选择","delivery.invalidated":"候选交付已失效","conversation.continue_revision":"已进入新的修订周期","conversation.close":"会话已关闭","conversation.reopen":"会话已重新打开"};return titles[type]||type}
function renderTrust(){const root=document.querySelector("#trust");root.replaceChildren();const detail=state.detail,conversation=detail.conversation,contract=detail.contracts.at(-1);const overview=el("section",undefined,"trust-section");overview.appendChild(el("h2","当前会话"));const dl=el("dl");for(const [key,value] of [["状态",labels[conversation.status]||conversation.status],["阶段进度",`${detail.progress?.percent||0}%`],["可信链",detail.integrity.valid?"有效":"异常"],["内部 Run",String(detail.runs.length)],["交付版本",String(detail.deliveries.length)]]){const row=el("div",undefined,"kv");row.append(el("dt",key),el("dd",value));dl.appendChild(row)}overview.appendChild(dl);root.appendChild(overview);const team=el("section",undefined,"trust-section");team.appendChild(el("h2",`Agent 团队 · 最多并行 ${detail.team?.max_parallel||4}`));for(const member of detail.team?.workers||[]){const active=(detail.team.active_stage_ids||[]).includes(member.stage_id),box=el("div",undefined,`team-member ${active?"active":member.status||"pending"}`);box.append(el("strong",`${member.role||"Agent"} · ${member.stage_id}`),el("small",`${member.provider||"待分配"} · ${active?"执行中":labels[member.status]||member.status} · attempt ${member.attempt||0}`));if(member.summary)box.appendChild(el("small",member.summary));team.appendChild(box)}if(!(detail.team?.workers||[]).length)team.appendChild(el("p","团队将在契约确认后自动组建。","hint"));root.appendChild(team);if(contract){const section=el("section",undefined,"trust-section"),box=el("div",undefined,"contract");section.appendChild(el("h2","置顶交付契约"));box.append(el("h3",`v${contract.version} · ${contract.workflow}/${contract.profile}`),el("p",contract.goal));const list=el("ul",undefined,"criteria");for(const text of contract.acceptance_criteria||[])list.appendChild(el("li",text));box.appendChild(list);const affected=contract.policy?.revision?.affected_stages||[];if(affected.length)box.appendChild(el("p",`本次修订影响：${affected.join("、")}`,"hint"));section.appendChild(box);root.appendChild(section)}renderStageDeliveries(root,contract);const deliveries=el("section",undefined,"trust-section");deliveries.appendChild(el("h2","候选与交付历史"));for(const item of [...detail.candidates].reverse()){const box=el("div",undefined,"delivery");box.append(el("strong",`候选 v${item.version} · ${labels[item.status]||item.status}`),el("small",`Run ${item.run_id}`));if(["verified","accepted","failed"].includes(item.status)){const link=el("a","查看 Evidence");link.href=`/api/v1/deliveries/${encodeURIComponent(item.candidate_id)}/evidence`;link.target="_blank";link.rel="noopener";box.appendChild(link)}deliveries.appendChild(box)}if(!detail.candidates.length)deliveries.appendChild(el("p","尚未生成交付候选。","hint"));root.appendChild(deliveries)}
function renderStageDeliveries(root,contract){const section=el("section",undefined,"trust-section");section.appendChild(el("h2","各阶段交付与标准"));section.appendChild(el("p","标准修订会生成新契约；已有 Evidence 保持不可变，并标明受影响的下游阶段。","hint"));for(const stage of state.detail.stage_deliveries||[]){const box=el("article",undefined,"stage-delivery"),head=el("header"),title=el("h3",`${stage.label} · ${stage.stage_id}`),status=el("span",labels[stage.status]||stage.status,`status ${stage.status}`);head.append(title,status);box.appendChild(head);const standards=el("div",undefined,"stage-block");standards.appendChild(el("strong","交付标准"));const list=el("ul");for(const item of stage.standards||[])list.appendChild(el("li",item.text));standards.appendChild(list);const edit=action("修订本阶段标准",()=>showStandardEditor(box,stage,contract),"quiet");edit.setAttribute("aria-label",`修订 ${stage.label} 阶段交付标准`);standards.appendChild(edit);box.appendChild(standards);const delivered=el("div",undefined,"stage-block");delivered.appendChild(el("strong","阶段交付"));delivered.appendChild(el("div",stage.summary||"尚未产生交付内容。","stage-output"));if(stage.output)delivered.appendChild(el("div",stage.output,"stage-output"));box.appendChild(delivered);const evidence=el("div",undefined,"stage-block");evidence.appendChild(el("strong",`Evidence · ${(stage.evidence||[]).length} 条 · Artifact · ${(stage.artifacts||[]).length} 个`));for(const item of stage.artifacts||[])evidence.appendChild(el("small",`${item.name} · ${item.digest||""}`));box.appendChild(evidence);section.appendChild(box)}root.appendChild(section)}
function showStandardEditor(box,stage,contract){if(box.querySelector(".standard-editor"))return;const editor=el("div",undefined,"standard-editor"),input=el("textarea"),controls=el("div",undefined,"recovery-actions");input.value=(stage.custom_standards||[]).join("\n");input.setAttribute("aria-label",`${stage.label} 阶段补充标准，每行一项`);controls.append(action("保存为新契约",()=>saveStageStandards(stage.stage_id,input.value,contract),"primary"),action("取消",()=>editor.remove(),"secondary"));editor.append(input,controls);box.appendChild(editor);input.focus()}
async function saveStageStandards(stageId,value,contract){const standards={...(contract.policy?.stage_standards||{})};standards[stageId]=value.split("\n").map(item=>item.trim()).filter(Boolean);try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"revise_contract",payload:{stage_standards:standards},idempotency_key:crypto.randomUUID()})});showNotice("已建立新契约版本；下一次执行将按修订标准验证");setTimeout(refreshDetail,500)}catch(error){showNotice(error.message,true)}}
async function sendAction(actionName,payload={}){try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:actionName,payload,idempotency_key:crypto.randomUUID()})});showNotice("操作已提交");setTimeout(refreshDetail,700)}catch(error){showNotice(error.message,true)}}
async function acceptDelivery(candidateId){try{await api(`/api/v1/deliveries/${encodeURIComponent(candidateId)}/accept`,{method:"POST"});showNotice("可信交付已接受并安全写回工作区");await refreshDetail()}catch(error){showNotice(error.message,true)}}
document.querySelector("#new-toggle").addEventListener("click",()=>document.querySelector("#new-form").classList.remove("hidden"));document.querySelector("#new-cancel").addEventListener("click",()=>document.querySelector("#new-form").classList.add("hidden"));document.querySelector("#new-form").addEventListener("submit",async event=>{event.preventDefault();try{const payload={goal:document.querySelector("#new-goal").value,title:document.querySelector("#new-title").value||null,profile:document.querySelector("#new-profile").value,provider:document.querySelector("#new-provider").value,auto_start:true};const result=await api("/api/v1/conversations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});document.querySelector("#new-form").reset();document.querySelector("#new-form").classList.add("hidden");await loadConversations();await selectConversation(result.conversation.conversation_id)}catch(error){showNotice(error.message,true)}});document.querySelector("#composer").addEventListener("submit",async event=>{event.preventDefault();const textarea=document.querySelector("#message"),intent=document.querySelector("#intent").value;try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content:textarea.value,intent,auto_start:["change","verify"].includes(intent)})});textarea.value="";showNotice("消息已发送");setTimeout(refreshDetail,600)}catch(error){showNotice(error.message,true)}});for(const filter of document.querySelectorAll(".filter"))filter.addEventListener("click",()=>{for(const item of document.querySelectorAll(".filter"))item.classList.remove("active");filter.classList.add("active");state.filter=filter.dataset.filter||"";loadConversations()});loadProviders();loadConversations().catch(error=>showNotice(error.message,true));
document.querySelector("#pair-form").addEventListener("submit",async event=>{event.preventDefault();try{const response=await fetch("/api/v1/auth/pair",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pairing_code:document.querySelector("#pair-code").value,device_label:document.querySelector("#device-label").value})});if(!response.ok)throw new Error("配对码无效或已过期");document.querySelector("#pairing").classList.add("hidden");await loadConversations();showNotice("设备已安全连接")}catch(error){showNotice(error.message,true)}});
</script>
</body>
</html>"""


__all__ = ["conversation_dashboard_html"]
