"""Conversation-first dashboard HTML kept separate from the HTTP adapter."""


_DASHBOARD_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="icon" href="data:,">
<link rel="stylesheet" href="/assets/vendor/xterm.css">
<title>MuxDev Conversation</title>
<style>
:root{color-scheme:light;--ink:#17202a;--muted:#667085;--line:#e4e7ec;--panel:#f7f9fc;--surface:#fff;--brand:#175cd3;--brand-soft:#eff8ff;--pass:#067647;--pass-soft:#ecfdf3;--warn:#b54708;--warn-soft:#fffaeb;--danger:#b42318;--danger-soft:#fef3f2;--shadow:0 1px 3px rgba(16,24,40,.08)}
*{box-sizing:border-box}html,body{height:100%;margin:0}body{font:14px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--ink);background:var(--panel)}button,textarea,select,input{font:inherit}button{cursor:pointer}.app{display:grid;grid-template-columns:290px minmax(420px,1fr) 340px;height:100vh;overflow:hidden}.rail,.trust{background:var(--surface);min-width:0}.rail{border-right:1px solid var(--line);display:flex;flex-direction:column}.trust{border-left:1px solid var(--line);overflow:auto}.brand{padding:20px;border-bottom:1px solid var(--line)}.brand h1{font-size:20px;margin:0}.brand p{color:var(--muted);margin:3px 0 0;font-size:12px}.new-button,.primary,.secondary,.quiet{border-radius:8px;padding:9px 12px;font-weight:700}.new-button,.primary{border:0;background:var(--brand);color:#fff}.new-button{width:100%;margin-top:14px}.secondary{border:1px solid var(--line);background:#fff;color:#344054}.quiet{border:0;background:transparent;color:var(--brand);padding:5px}.filters{display:flex;gap:6px;padding:12px 14px;border-bottom:1px solid var(--line);overflow:auto}.filter{white-space:nowrap;border:0;border-radius:999px;padding:5px 9px;background:var(--panel);color:var(--muted)}.filter.active{background:var(--brand-soft);color:var(--brand);font-weight:700}.conversations{overflow:auto;padding:8px}.conversation-item{display:block;width:100%;border:0;border-radius:10px;background:transparent;text-align:left;padding:11px;margin-bottom:3px;color:inherit}.conversation-item:hover,.conversation-item.active{background:var(--panel)}.conversation-title{font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.conversation-meta{display:flex;justify-content:space-between;gap:8px;color:var(--muted);font-size:12px;margin-top:4px}.status{font-weight:700}.status.awaiting_acceptance,.status.delivered{color:var(--pass)}.status.needs_user{color:var(--danger)}.status.verifying,.status.recovering,.status.working{color:var(--warn)}
.room{display:flex;min-width:0;flex-direction:column;background:#fff}.room-header{min-height:72px;padding:14px 20px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:16px}.room-title{font-size:17px;font-weight:800}.room-subtitle{color:var(--muted);font-size:12px;margin-top:3px}.room-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.timeline{flex:1;overflow:auto;padding:22px max(20px,6vw);background:linear-gradient(#fff,#fbfcfe)}.empty{height:100%;display:grid;place-items:center;color:var(--muted);text-align:center}.empty strong{display:block;color:var(--ink);font-size:20px;margin-bottom:6px}.event{max-width:760px;margin:0 auto 14px}.message{display:flex;gap:10px}.actor{width:34px;height:34px;border-radius:9px;background:var(--brand-soft);color:var(--brand);display:grid;place-items:center;font-weight:800;flex:0 0 auto}.message-body{min-width:0;flex:1}.message-head{font-size:12px;color:var(--muted);margin-bottom:4px}.bubble{display:inline-block;max-width:100%;padding:10px 12px;border-radius:4px 12px 12px 12px;background:var(--panel);white-space:pre-wrap;overflow-wrap:anywhere}.event.developer .message{flex-direction:row-reverse}.event.developer .message-head{text-align:right}.event.developer .bubble{float:right;background:var(--brand);color:#fff;border-radius:12px 4px 12px 12px}.card{border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:var(--shadow);padding:14px 16px}.card.pass{border-left:4px solid var(--pass)}.card.warn{border-left:4px solid var(--warn)}.card.danger{border-left:4px solid var(--danger)}.eyebrow{text-transform:uppercase;letter-spacing:.07em;font-weight:800;font-size:10px;color:var(--muted)}.card-title{font-weight:800;margin-top:4px}.card-copy{color:#475467;margin-top:5px;white-space:pre-wrap}.composer{border-top:1px solid var(--line);padding:12px 18px;background:#fff}.composer-box{max-width:850px;margin:auto;border:1px solid #d0d5dd;border-radius:12px;padding:10px;box-shadow:0 1px 2px rgba(16,24,40,.04)}textarea{width:100%;min-height:58px;max-height:180px;resize:vertical;border:0;outline:0;padding:4px;background:transparent}.composer-tools{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:7px}.composer-tools select{border:1px solid var(--line);border-radius:7px;padding:6px;color:#475467;background:#fff}.hint{font-size:12px;color:var(--muted)}
.progress-wrap{width:min(420px,52vw);margin-top:7px}.progress-meta{display:flex;justify-content:space-between;gap:12px;color:var(--muted);font-size:11px}.progress-track{height:7px;border-radius:999px;background:#eaecf0;overflow:hidden;margin-top:4px}.progress-bar{height:100%;width:0;background:var(--brand);transition:width .3s ease}.progress-bar.waiting_user{background:var(--warn)}.progress-bar.failed{background:var(--danger)}.progress-bar.completed{background:var(--pass)}.question-options{display:grid;gap:7px;margin-top:12px}.question-option{text-align:left;border:1px solid var(--line);border-radius:9px;background:#fff;padding:9px}.question-option.recommended{border-color:var(--brand);background:var(--brand-soft)}.question-option small{display:block;color:var(--muted);font-weight:400}.question-custom{display:flex;gap:7px;margin-top:9px}.question-custom input{flex:1;min-width:0;border:1px solid var(--line);border-radius:8px;padding:8px}.countdown{font-size:12px;color:var(--warn);margin-top:8px}.stage-delivery{border:1px solid var(--line);border-radius:10px;padding:11px;margin-top:9px}.stage-delivery header{display:flex;justify-content:space-between;gap:8px}.stage-delivery h3{font-size:13px;margin:0}.stage-block{margin-top:9px}.stage-block strong{font-size:11px;color:var(--muted)}.stage-block ul{margin:5px 0 0;padding-left:18px}.stage-output{white-space:pre-wrap;max-height:150px;overflow:auto;font-size:12px;color:#475467}.standard-editor{margin-top:8px}.standard-editor textarea{border:1px solid var(--line);border-radius:8px;min-height:80px}.standard-editor .recovery-actions{justify-content:flex-end}
.trust-section{padding:18px;border-bottom:1px solid var(--line)}.trust-section h2{font-size:13px;margin:0 0 12px}.kv{display:grid;grid-template-columns:100px 1fr;gap:8px;font-size:12px;margin-bottom:8px}.kv dt{color:var(--muted)}.kv dd{margin:0;overflow-wrap:anywhere}.contract{padding:12px;border-radius:10px;background:var(--panel)}.contract h3{font-size:14px;margin:0 0 6px}.contract p{margin:0;color:#475467}.criteria{padding-left:18px;margin:8px 0 0}.delivery,.team-member{border:1px solid var(--line);border-radius:9px;padding:10px;margin-top:8px}.delivery strong,.team-member strong{display:block}.delivery small,.team-member small{display:block;color:var(--muted);overflow-wrap:anywhere}.team-member.active{border-color:var(--warn);background:var(--warn-soft)}.team-member.failed{border-color:var(--danger)}.team-member.completed{border-color:#abefc6}.failure-meta{display:flex;gap:8px;flex-wrap:wrap;color:var(--muted);font-size:12px;margin-top:7px}.failure-details{margin:8px 0 0;padding-left:18px;color:#475467}.recovery-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.recovery-attempt{font-size:12px;color:#475467;margin-top:5px}.command{font:12px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace;background:var(--panel);padding:7px;border-radius:7px;margin-top:7px;overflow-wrap:anywhere}.notice{position:fixed;left:50%;top:16px;transform:translateX(-50%);z-index:10;background:#101828;color:#fff;padding:9px 14px;border-radius:8px;box-shadow:var(--shadow)}.notice.error{background:var(--danger)}.new-panel{padding:14px;border-bottom:1px solid var(--line);background:var(--panel)}.new-panel input,.new-panel textarea,.new-panel select{width:100%;border:1px solid var(--line);border-radius:8px;background:#fff;padding:8px;margin-bottom:8px}.new-panel textarea{min-height:84px}.new-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pairing{position:fixed;inset:0;z-index:20;display:grid;place-items:center;background:rgba(16,24,40,.48);padding:20px}.pairing-card{width:min(420px,100%);background:#fff;border-radius:16px;padding:24px;box-shadow:0 18px 48px rgba(16,24,40,.22)}.pairing-card h2{margin:0 0 6px}.pairing-card p{color:var(--muted);margin:0 0 16px}.pairing-card input{width:100%;border:1px solid var(--line);border-radius:8px;padding:10px;margin-bottom:10px}.pairing-card button{width:100%}.hidden{display:none!important}
@media(max-width:1050px){.app{grid-template-columns:250px 1fr}.trust{display:none}}@media(max-width:720px){.app{display:block;height:auto;min-height:100vh}.rail{height:auto;border-right:0}.conversations{display:flex;overflow:auto}.conversation-item{min-width:220px}.room{min-height:calc(100vh - 210px)}.trust{display:block;border-left:0;border-top:1px solid var(--line)}.room-header{display:block}.room-actions{justify-content:flex-start;margin-top:10px}.room-actions button{max-width:100%;white-space:normal}.timeline{padding:18px 12px}.message-body{min-width:0}.bubble{max-width:calc(100vw - 74px);overflow-wrap:anywhere}.hint{display:none}}
.room{min-height:0;overflow:hidden}.timeline{min-height:0}.delivery-card{border:1px solid var(--line);border-left:4px solid var(--warn);border-radius:14px;background:#fff;box-shadow:var(--shadow);padding:18px}.delivery-card.ready,.delivery-card.written{border-left-color:var(--pass)}.delivery-card.blocked,.delivery-card.stale{border-left-color:var(--danger)}.delivery-card h3{margin:4px 0 2px;font-size:17px}.delivery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.delivery-fact{border-radius:9px;background:var(--panel);padding:10px}.delivery-fact strong{display:block;font-size:11px;color:var(--muted);margin-bottom:3px}.delivery-file{display:flex;justify-content:space-between;gap:8px;border-top:1px solid var(--line);padding:6px 0;font-size:12px}.delivery-actions{display:flex;align-items:flex-start;gap:10px;flex-wrap:wrap;margin-top:14px}.delivery-actions .hint{flex:1;min-width:220px}.status-text{font-weight:800}.status-text.passed,.status-text.ready,.status-text.written{color:var(--pass)}.status-text.failed,.status-text.blocked,.status-text.stale{color:var(--danger)}.status-text.pending,.status-text.verifying{color:var(--warn)}
.standard-stage{border:1px solid var(--line);border-radius:10px;padding:11px;margin-top:9px}.standard-stage>summary{cursor:pointer;list-style:none;display:flex;justify-content:space-between;gap:8px;font-weight:800}.standard-stage>summary::-webkit-details-marker{display:none}.standard-stage>summary:focus-visible,button:focus-visible,select:focus-visible,input:focus-visible,textarea:focus-visible,a:focus-visible{outline:3px solid #84adff;outline-offset:2px}.standard-three{display:grid;gap:8px;margin-top:10px}.standard-three div{border-left:2px solid var(--line);padding-left:9px}.standard-three strong{display:block;font-size:11px;color:var(--muted)}.standard-list{list-style:none;margin:10px 0 0;padding:0}.standard-item{display:grid;grid-template-columns:auto 1fr auto;align-items:start;gap:7px;padding:7px 0;border-top:1px solid var(--line);font-size:12px}.badge{display:inline-block;border-radius:999px;padding:2px 7px;background:var(--panel);color:var(--muted);font-size:10px;font-weight:800}.badge.builtin{background:#f2f4f7}.badge.conversation{background:var(--brand-soft);color:var(--brand)}.standard-edit-form{border:1px solid #84adff;border-radius:10px;padding:11px;margin-top:10px;background:#f8fbff}.standard-edit-form label{display:block;font-size:11px;font-weight:800;color:var(--muted);margin:8px 0 3px}.standard-edit-form input,.standard-edit-form select{width:100%;border:1px solid var(--line);border-radius:7px;background:#fff;padding:7px}.standard-rule-row{border-top:1px solid var(--line);padding-top:10px;margin-top:10px}.standard-preview{background:var(--warn-soft);border-radius:8px;padding:9px;margin-top:10px;font-size:12px}.internal-details{border-top:1px solid var(--line);padding-top:12px;margin-top:12px}.internal-details>summary{cursor:pointer;color:var(--muted);font-weight:700}.primary:disabled{cursor:not-allowed;background:#98a2b3}.mini-list{margin:5px 0 0;padding-left:18px}.trust-copy{color:#475467;margin:0}.trust-subhead{font-size:11px;color:var(--muted);font-weight:800;margin:12px 0 5px}
@media(min-width:1200px){.app{grid-template-columns:280px minmax(420px,1fr) 390px}}
@media(max-width:1050px) and (min-width:861px){.app{grid-template-columns:220px minmax(0,1fr) 300px}.trust{display:block}.timeline{padding:18px}.delivery-grid{grid-template-columns:1fr}}
@media(max-width:500px){.delivery-grid{grid-template-columns:1fr}.delivery-actions{display:block}.delivery-actions button{width:100%;margin-bottom:8px}.standard-item{grid-template-columns:auto 1fr}.standard-item .status-text{grid-column:2}}
@media(max-width:720px){.room{overflow:visible}.timeline{overflow:visible}.delivery-actions .hint{display:block;margin-bottom:10px}}
.dag{display:grid;gap:8px;margin-top:10px}.dag-node{border:1px solid var(--line);border-radius:9px;padding:10px;background:#fff}.dag-node header{display:flex;justify-content:space-between;gap:8px}.dag-node small{display:block;color:var(--muted);margin-top:4px}.terminal-drawer{border-top:1px solid var(--line);background:#101828;color:#f2f4f7;max-height:44vh;display:flex;flex-direction:column}.terminal-head{display:flex;align-items:center;gap:7px;padding:7px 10px;background:#1d2939;overflow:auto}.terminal-tabs{display:flex;gap:6px;flex:1}.terminal-tab{border:0;border-radius:6px;padding:5px 9px;background:#344054;color:#d0d5dd;white-space:nowrap}.terminal-tab.active{background:#fff;color:#101828}.terminal-screen{height:280px;padding:4px}.terminal-tools{display:flex;gap:5px;padding:7px 10px;background:#1d2939;overflow:auto}.terminal-key{border:1px solid #475467;border-radius:6px;background:#344054;color:#fff;padding:6px 10px;white-space:nowrap}.assignment-badge{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted)}
@media(max-width:720px){.terminal-drawer{position:sticky;bottom:0;max-height:54vh}.terminal-screen{height:240px}.terminal-tools{padding-bottom:max(7px,env(safe-area-inset-bottom))}}
</style>
</head>
<body>
<div id="notice" class="notice hidden" role="status"></div>
<section id="pairing" class="pairing hidden"><form id="pair-form" class="pairing-card"><h2>连接这台开发机器</h2><p>输入本地 MuxDev 终端显示的一次性配对码。每台浏览器会获得独立、可撤销的设备身份。</p><input id="device-label" value="我的浏览器" required aria-label="设备名称"><input id="pair-code" required autocomplete="one-time-code" aria-label="一次性配对码" placeholder="一次性配对码"><button class="primary" type="submit">安全连接</button></form></section>
<main class="app">
  <aside class="rail">
    <div class="brand"><h1>MuxDev Conversation</h1><p>一个会话，完成一次可信开发交付</p><button id="new-toggle" class="new-button" type="button">新建任务会话</button></div>
    <form id="new-form" class="new-panel hidden">
      <input id="new-title" aria-label="会话名称" placeholder="会话名称（可选）">
      <textarea id="new-goal" required aria-label="任务目标" placeholder="描述需要完成的开发任务"></textarea>
      <div class="new-grid"><select id="new-mode" aria-label="执行模式"><option value="direct">直接执行</option><option value="orchestrated">编排执行</option></select><select id="new-profile" aria-label="交付级别"><option value="lite">Lite</option><option value="standard" selected>Standard</option><option value="strict">Strict</option></select></div>
      <select id="new-agent" aria-label="主要 Agent"><option value="mock">mock · 流程演示</option></select>
      <p class="hint">直接模式由一个主要实现 Agent 端到端负责；只有显式选择编排执行，编排者才会先展示 DAG 与分工并等待一次确认。真实开发请选择可用 Agent；mock 只验证流程。Standard/Strict 需要独立 Reviewer。</p>
      <button class="primary" type="submit">创建并开始</button>
      <button id="new-cancel" class="quiet" type="button">取消</button>
    </form>
    <div class="filters"><button class="filter active" data-filter="" type="button">全部</button><button class="filter" data-filter="needs_user" type="button">需要你处理</button><button class="filter" data-filter="awaiting_acceptance" type="button">待接受</button></div>
    <nav id="conversations" class="conversations" aria-label="任务会话"></nav>
  </aside>
  <section class="room">
    <header class="room-header"><div><div id="room-title" class="room-title">选择一个任务会话</div><div id="room-subtitle" class="room-subtitle">持续沟通、自动修复并完成可信交付</div><div id="room-progress" class="progress-wrap hidden"><div class="progress-meta"><span id="progress-label"></span><span id="progress-value"></span></div><div class="progress-track" role="progressbar" aria-label="可信交付阶段进度" aria-valuemin="0" aria-valuemax="100"><div id="progress-bar" class="progress-bar"></div></div></div></div><div id="room-actions" class="room-actions"></div></header>
    <div id="timeline" class="timeline" aria-live="polite" aria-label="会话执行时间线"><div class="empty"><div><strong>让开发任务在一个会话中走完</strong>创建会话后，需求、执行、自愈、验证与交付都会保留在这里。</div></div></div>
    <form id="composer" class="composer hidden"><div class="composer-box"><textarea id="message" required aria-label="发送消息" placeholder="发给主 Agent，或使用 @agent 定向协作"></textarea><div class="composer-tools"><div><select id="intent" aria-label="消息用途"><option value="message">发给当前 Agent</option><option value="consult">只读咨询</option><option value="write">隔离写任务</option></select><span class="hint">普通消息默认发给主 Agent；@agent 才会唤起其他 Agent</span></div><button class="primary" type="submit">发送</button></div></div></form>
    <section id="terminal-drawer" class="terminal-drawer hidden" aria-label="多 Agent Web 终端"><div class="terminal-head"><div id="terminal-tabs" class="terminal-tabs"></div><button id="terminal-takeover" class="terminal-key" type="button">接管终端</button><button id="terminal-close" class="terminal-key" type="button">收起</button></div><div id="terminal-screen" class="terminal-screen"></div><div class="terminal-tools"><button class="terminal-key" data-key="\u001b" type="button">Esc</button><button class="terminal-key" data-key="\u0003" type="button">Ctrl+C</button><button class="terminal-key" data-key="\t" type="button">Tab</button><button class="terminal-key" data-key="\u001b[D" type="button">←</button><button class="terminal-key" data-key="\u001b[A" type="button">↑</button><button class="terminal-key" data-key="\u001b[B" type="button">↓</button><button class="terminal-key" data-key="\u001b[C" type="button">→</button><button class="terminal-key" data-key="\u001b[2J\u001b[H" type="button">清屏</button></div></section>
  </section>
  <aside id="trust" class="trust"><div class="trust-section"><h2>本次任务与交付标准</h2><p class="hint">选择会话后查看任务验收、可靠完成标准与当前交付。</p></div></aside>
</main>
<script src="/assets/vendor/xterm.js"></script>
<script src="/assets/vendor/addon-fit.js"></script>
<script>
const state={conversations:[],selected:null,detail:null,filter:"",source:null,timelineRequest:0,terminal:null,fit:null,socket:null,sessionId:null,lease:false};
const labels={clarifying:"澄清中",working:"工作中",needs_user:"需要你处理",candidate_ready:"候选就绪",verifying:"验证中",recovering:"自愈中",awaiting_acceptance:"等待接受",delivered:"已交付",closed:"已关闭",pending:"等待中",running:"执行中",waiting_user:"等待确认",completed:"已完成",skipped:"已跳过",verified:"已验证",accepted:"已接受",failed:"未通过",invalidated:"已失效"};
function el(tag,text,className){const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=text;return item}
function showNotice(text,error=false){const item=document.querySelector("#notice");item.textContent=text;item.className=`notice${error?" error":""}`;setTimeout(()=>item.classList.add("hidden"),3500)}
async function api(url,options){const response=await fetch(url,options);if(response.status===401){document.querySelector("#pairing").classList.remove("hidden");throw new Error("需要先配对这台设备")}if(!response.ok){let message=`HTTP ${response.status}`;try{const payload=await response.json();message=payload.detail||message}catch(parseError){message=`${message} · ${String(parseError)}`}throw new Error(message)}return response.json()}
function formatTime(value){if(!value)return "";try{return new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}catch{return value}}
async function loadConversations(){const query=state.filter?`?status=${encodeURIComponent(state.filter)}`:"";state.conversations=await api(`/api/v2/conversations${query}`);renderConversations();if(!state.selected&&state.conversations.length)await selectConversation(state.conversations[0].conversation_id)}
async function loadProviders(){const select=document.querySelector("#new-agent");try{const agents=await api("/api/v2/agents"),usable=agents.filter(item=>item.enabled&&item.available);select.replaceChildren();for(const item of usable){const option=el("option",`${item.display_name} · ${item.agent_id}${item.can_orchestrate?" · 可编排":""}`);option.value=item.agent_id;option.dataset.orchestrator=String(item.can_orchestrate);select.appendChild(option)}if(!usable.length){const option=el("option","mock · 流程演示");option.value="mock";select.appendChild(option)}select.value=usable.find(item=>item.agent_id==="codex")?.agent_id||usable[0]?.agent_id||"mock"}catch(error){showNotice(`Agent 列表加载失败：${error.message}`,true);select.value="mock"}}
function renderConversations(){const root=document.querySelector("#conversations");root.replaceChildren();for(const item of state.conversations){const button=el("button",undefined,`conversation-item${item.conversation_id===state.selected?" active":""}`);button.type="button";button.addEventListener("click",()=>selectConversation(item.conversation_id));const title=el("div",item.title,"conversation-title"),meta=el("div",undefined,"conversation-meta"),status=el("span",labels[item.status]||item.status,`status ${item.status}`),time=el("span",formatTime(item.updated_at));meta.append(status,time);button.append(title,meta);root.appendChild(button)}if(!state.conversations.length)root.appendChild(el("div","还没有符合条件的会话。","hint"))}
async function selectConversation(id){state.selected=id;renderConversations();if(state.source)state.source.close();await refreshDetail();state.source=new EventSource(`/api/v1/conversations/${encodeURIComponent(id)}/events`);state.source.onopen=()=>refreshDetail();state.source.addEventListener("conversation",()=>refreshDetail());state.source.onerror=()=>{} }
async function refreshDetail(){if(!state.selected)return;state.detail=await api(`/api/v2/conversations/${encodeURIComponent(state.selected)}`);renderDetail();await loadConversations()}
function renderDetail(){const detail=state.detail,conversation=detail.conversation;document.querySelector("#room-title").textContent=conversation.title;document.querySelector("#room-subtitle").textContent=`${labels[conversation.status]||conversation.status} · ${conversation.mode||"legacy_pipeline"} · ${conversation.conversation_id}`;document.querySelector("#composer").classList.toggle("hidden",conversation.status==="closed");renderProgress(detail.progress,detail.assignments||[],conversation.mode);renderActions(conversation,detail.candidates,detail.recovery,detail.interactions||[]);renderTimeline();renderTrust();renderTerminalTabs()}
function renderProgress(progress,assignments,mode){const root=document.querySelector("#room-progress"),bar=document.querySelector("#progress-bar"),track=root.querySelector(".progress-track");root.classList.remove("hidden");if(mode&&mode!=="legacy_pipeline"){const completed=assignments.filter(item=>["completed","cancelled"].includes(item.status)).length,active=assignments.filter(item=>["running","merging","verifying"].includes(item.status)).map(item=>item.title).join("、");document.querySelector("#progress-label").textContent=active?`执行中：${active}`:"按 Runtime 节点状态显示";document.querySelector("#progress-value").textContent=`${completed}/${assignments.length} Assignments`;track.hidden=true;return}track.hidden=false;const value=progress?.percent||0;document.querySelector("#progress-label").textContent=progress?.label||"等待开始";document.querySelector("#progress-value").textContent=`${value}% · ${progress?.completed_stages||0}/${progress?.total_stages||0} 阶段`;bar.style.width=`${value}%`;bar.className=`progress-bar ${progress?.state||"pending"}`;track.setAttribute("aria-valuenow",String(value));track.setAttribute("aria-valuetext",`${progress?.label||"等待开始"}，${value}%`)}
function action(text,handler,className){const button=el("button",text,className);button.type="button";button.addEventListener("click",handler);return button}
function appendRecoveryActions(root,items,compact=false){for(const item of items){const recoverable=["auto","fix-output","retry","switch-provider"].includes(item.action),restart=item.action==="start_work",label=item.label||item.action;if(recoverable||restart){const button=action(label,()=>restart?sendAction("start_work"):sendAction("auto_recover",{recovery_action:item.action}),compact?"primary":"secondary");button.setAttribute("aria-label",`${label}：${item.description||"执行恢复动作"}`);root.appendChild(button)}else if(item.command){const button=action(label,()=>copyCommand(item.command),"secondary");button.setAttribute("aria-label",`${label}：复制命令 ${item.command}`);root.appendChild(button)}}}
async function copyCommand(command){try{await navigator.clipboard.writeText(command);showNotice("诊断命令已复制")}catch{showNotice(`请手动执行：${command}`,true)}}
function renderTimeline(){
  const root=document.querySelector("#timeline"),requestId=++state.timelineRequest;
  api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/events`).then(events=>{
    if(requestId!==state.timelineRequest)return;root.replaceChildren();let previous="";
    for(const event of events){if(!visibleEvent(event))continue;const key=eventKey(event);if(key===previous)continue;previous=key;root.appendChild(renderEvent(event))}
    requestAnimationFrame(()=>{const delivery=root.querySelector(".delivery-card");if(delivery&&window.innerWidth<=720)delivery.scrollIntoView({block:"start"});else root.scrollTop=root.scrollHeight});
  }).catch(error=>showNotice(error.message,true));
}
function visibleEvent(event){
  if(["action.claimed","run.requested","provider.session_bound"].includes(event.type))return false;
  if(event.type!=="run.event")return true;
  return (event.payload?.source_type||"")==="interaction.requested";
}
function eventKey(event){const payload=event.payload||{};return `${event.type}:${payload.source_type||""}:${payload.stage_id||""}:${payload.attempt||""}:${payload.status||""}:${payload.summary||""}`}
function renderEvent(event){const wrapper=el("article",undefined,`event ${event.actor}`),payload=event.payload||{};if(event.type==="user.message"||event.type.endsWith(".message")){const row=el("div",undefined,"message"),actor=el("div",event.actor==="developer"?"你":event.actor==="reviewer"?"评":event.actor==="implementer"?"实":"M","actor"),body=el("div",undefined,"message-body"),head=el("div",`${actorLabel(event.actor)} · ${formatTime(event.created_at)}`,"message-head"),bubble=el("div",payload.content||payload.summary||event.type,"bubble");body.append(head,bubble);row.append(actor,body);wrapper.appendChild(row);return wrapper}let tone="";if(event.type==="delivery.verified"||event.type==="delivery.accepted"||payload.source_type==="worker.completed")tone=" pass";else if(event.type.includes("failed")||event.type.includes("needs_user")||event.type.includes("invalidated")||event.type==="run.orphaned"||payload.source_type==="worker.failed")tone=" danger";else if(event.type.startsWith("run.")||event.type.includes("recover")||event.type.startsWith("interaction.")||payload.source_type==="worker.waiting"||payload.source_type==="interaction.requested")tone=" warn";const card=el("div",undefined,`card${tone}`);card.append(el("div",eventLabel(event),"eyebrow"),el("div",runEventTitle(payload)||summaryLabel(payload.summary||payload.message)||eventTitle(event.type),"card-title"));if(payload.source_type==="interaction.requested")renderInteraction(card,payload);else if(event.type==="delivery.needs_user"||event.type==="run.failed_to_start"||event.type==="recovery.failed"||event.type==="run.orphaned")renderFailure(card,payload);else if(event.type==="contract.revised"&&(payload.affected_stages||[]).length)card.appendChild(el("div",`需重新验证：${payload.affected_stages.join("、")}`,"card-copy"));else if(payload.next_action)card.appendChild(el("div",payload.next_action,"card-copy"));wrapper.appendChild(card);return wrapper}
function runEventTitle(payload){const source=payload.source_type||"";if(source==="run.initializing")return "Run 已建立，正在预检 Agent 团队";if(source==="team.resolved")return `Agent 团队已就绪 · 最多并行 ${payload.max_parallel||4}`;if(source==="worker.started")return `${payload.role||"Agent"} · ${payload.provider||"待分配"} 开始 ${payload.stage_id||"阶段"}`;if(source==="worker.completed")return `${payload.role||"Agent"} · ${payload.provider||"待分配"} 已完成 ${payload.stage_id||"阶段"}`;if(source==="worker.waiting")return `${payload.role||"Agent"} 正在等待你的选择`;if(source==="worker.failed")return `${payload.role||"Agent"} · ${payload.provider||"待分配"} 执行失败`;if(source==="interaction.requested")return payload.question||"Agent 需要确认一项需求";if(source==="interaction.responded")return payload.defaulted?"1 分钟未回复，已采用推荐项":"问题已回答，准备继续执行";if(source==="interaction.resume")return "已根据你的回答继续当前阶段";if(source==="supervisor.fanout.started")return `并行执行：${(payload.stages||[]).join("、")}`;if(source==="supervisor.fanout.completed")return `并行阶段已按固定顺序合并`;return ""}
function renderInteraction(card,payload){const interaction=(state.detail.interactions||[]).find(item=>item.interaction_id===payload.interaction_id)||payload,pending=interaction.status==="pending"||!interaction.status;if(interaction.reason)card.appendChild(el("div",interaction.reason,"card-copy"));const meta=el("div",undefined,"failure-meta");meta.append(el("span",interaction.blocking?"必须人工确认":"低风险澄清"),el("span",`阶段 ${interaction.stage_id||payload.stage_id||"当前"}`));card.appendChild(meta);if(!pending){card.appendChild(el("div",interaction.status==="approved"?"已批准":interaction.status==="rejected"?"已拒绝":"已回答","card-copy"));return}const options=el("div",undefined,"question-options");for(const item of interaction.options||[]){const button=el("button",undefined,`question-option${item.id===interaction.recommended_option_id?" recommended":""}`);button.type="button";button.appendChild(el("strong",`${item.label}${item.id===interaction.recommended_option_id?"（推荐）":""}`));if(item.description)button.appendChild(el("small",item.description));button.addEventListener("click",()=>answerInteraction(interaction.interaction_id,item.id));options.appendChild(button)}card.appendChild(options);if(interaction.allow_custom_input!==false){const form=el("form",undefined,"question-custom"),input=el("input"),send=el("button","提交说明","secondary");input.placeholder="也可以自行输入";input.setAttribute("aria-label","自定义回答");send.type="submit";form.addEventListener("submit",event=>{event.preventDefault();if(input.value.trim())answerInteraction(interaction.interaction_id,null,input.value.trim())});form.append(input,send);card.appendChild(form)}const countdown=el("div",undefined,"countdown");if(interaction.blocking)countdown.textContent="此问题不会超时自动选择，收到明确确认前执行保持暂停。";else if(interaction.expires_at){const seconds=Math.max(0,Math.ceil((new Date(interaction.expires_at)-Date.now())/1000));countdown.textContent=`${seconds} 秒后未回复将采用推荐项。`}card.appendChild(countdown)}
async function answerInteraction(interactionId,optionId,customInput){try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"respond_interaction",payload:{interaction_id:interactionId,option_id:optionId||null,custom_input:customInput||null},idempotency_key:crypto.randomUUID()})});showNotice("回答已提交，Agent 将从当前阶段继续");setTimeout(refreshDetail,500)}catch(error){showNotice(error.message,true)}}
function renderFailure(card,payload){const failure=payload.failure||{},recovery=payload.recovery||{};const meta=el("div",undefined,"failure-meta");for(const text of [failure.stage_id&&`阶段 ${failure.stage_id}`,failure.provider&&`Agent ${failure.provider}`,failure.returncode!==undefined&&failure.returncode!==null&&`退出码 ${failure.returncode}`,failure.code&&`原因 ${failure.code}`].filter(Boolean))meta.appendChild(el("span",text));if(meta.childNodes.length)card.appendChild(meta);if(failure.summary)card.appendChild(el("div",failure.summary,"card-copy"));if((failure.details||[]).length){const details=el("ul",undefined,"failure-details");for(const text of failure.details)details.appendChild(el("li",text));card.appendChild(details)}for(const item of recovery.attempts||[])card.appendChild(el("div",`${item.action} · ${item.provider||"当前 Agent"} · ${item.status}`,"recovery-attempt"));if(recovery.workspace_message)card.appendChild(el("div",recovery.workspace_message,"card-copy"));const controls=el("div",undefined,"recovery-actions");appendRecoveryActions(controls,payload.next_actions||[],false);if(controls.childNodes.length)card.appendChild(controls);if(payload.candidate_id){const link=el("a","查看 Evidence");link.href=`/api/v1/deliveries/${encodeURIComponent(payload.candidate_id)}/evidence`;link.target="_blank";link.rel="noopener";link.setAttribute("aria-label","查看本次失败的 Evidence");card.appendChild(link)}}
function actorLabel(actor){return {developer:"开发者",implementer:"实施者",reviewer:"独立评审",supervisor:"MuxDev"}[actor]||actor}
function eventLabel(event){if(event.type==="run.event")return "执行状态";return {"contract.created":"交付契约","contract.revised":"契约修订","run.requested":"执行周期","delivery.verified":"可信候选","delivery.accepted":"已接受交付","delivery.invalidated":"候选失效"}[event.type]||event.type.replaceAll("."," · ")}
function summaryLabel(value){return {running:"正在执行并收集运行时事实",blocked:"当前执行需要处理",awaiting_approval:"正在等待你的确认"}[value]||value}
function eventTitle(type){const titles={"contract.created":"交付契约已建立","contract.revised":"交付契约已修订","workspace.prepared":"隔离工作树已准备","run.requested":"已开始新的执行周期","run.orphaned":"后台执行已中断，可重新建立 Run","run.event":"Run 事实已更新","interaction.awaiting_user":"执行已安全暂停，等待你的选择","interaction.answer_received":"已收到你的选择","delivery.invalidated":"候选交付已失效","conversation.continue_revision":"已进入新的修订周期","conversation.close":"会话已关闭","conversation.reopen":"会话已重新打开"};return titles[type]||type}
const renderEventWithoutDeliveryCard=renderEvent;
function renderActions(conversation,candidates,recovery,interactions){
  const root=document.querySelector("#room-actions");root.replaceChildren();
  const plan=(state.detail?.plans||[]).find(item=>item.plan_id===conversation.active_plan_id);
  if(plan?.status==="awaiting_approval")root.append(action("确认 DAG 与分工",()=>approvePlan(plan.plan_id),"primary"));
  const hasQuestion=interactions.some(item=>item.status==="pending");
  if(conversation.status==="needs_user"&&!hasQuestion&&conversation.mode==="legacy_pipeline")appendRecoveryActions(root,recovery?.next_actions||[],true);
  if(conversation.status==="needs_user"&&conversation.mode!=="legacy_pipeline"&&candidates.some(item=>item.status==="verifying"))root.append(action("确认 Strict 验证",approveVerification,"primary"));
  if(conversation.status==="awaiting_acceptance")root.append(action("继续修改",()=>sendAction("continue_revision"),"secondary"));
  if(conversation.status==="delivered")root.append(action("继续修订",()=>sendAction("continue_revision"),"secondary"),action("关闭会话",()=>sendAction("close"),"secondary"));
  if(conversation.status==="closed")root.append(action("重新打开",()=>sendAction("reopen"),"secondary"));
  if(["clarifying","working"].includes(conversation.status)&&conversation.mode==="legacy_pipeline")root.append(action("开始验证",()=>sendAction("verify"),"primary"));
};
renderEvent=function(event){
  const delivery=state.detail?.active_delivery,payload=event.payload||{};
  if(delivery&&payload.candidate_id===delivery.candidate_id&&["delivery.verified","delivery.needs_user","delivery.invalidated","delivery.accepted"].includes(event.type)){
    const wrapper=el("article",undefined,`event ${event.actor}`);wrapper.appendChild(renderDeliveryCard(delivery));return wrapper;
  }
  return renderEventWithoutDeliveryCard(event);
};
function renderDeliveryCard(delivery){
  const card=el("section",undefined,`delivery-card ${delivery.state||"blocked"}`);
  card.setAttribute("aria-label","本次交付");
  card.append(el("div","本次交付","eyebrow"),el("h3",delivery.status_label||"暂不能交付"),el("div",delivery.change_summary||"尚无变更摘要。","card-copy"));
  const facts=el("div",undefined,"delivery-grid"),standard=delivery.standard_summary||{};
  const values=[
    ["任务目标",delivery.task_goal||"未说明"],
    ["文件变化",`${(delivery.changed_files||[]).length} 个文件`],
    ["交付标准",`${standard.pre_accept_passed||0}/${standard.pre_accept_total||0} 已通过`],
    ["运行检查",`${(delivery.checks||[]).filter(item=>item.status==="passed").length}/${(delivery.checks||[]).length} 已通过`],
    ["评审",`${(delivery.reviews||[]).length} 份${(delivery.reviews||[]).some(item=>item.independent)?" · 含独立评审":""}`],
    ["证据完整性",delivery.evidence_integrity?.valid?"有效":delivery.evidence_integrity?.available?"无效":"不可用"],
  ];
  for(const [key,value] of values){const fact=el("div",undefined,"delivery-fact");fact.append(el("strong",key),el("span",value));facts.appendChild(fact)}card.appendChild(facts);
  if((delivery.changed_files||[]).length){const list=el("div");for(const path of delivery.changed_files.slice(0,4))list.appendChild(el("div",path,"delivery-file"));card.appendChild(list)}
  if((delivery.blocking_items||[]).length){const block=el("div",undefined,"card-copy"),list=el("ul",undefined,"mini-list");block.appendChild(el("strong","当前阻止交付"));for(const item of delivery.blocking_items)list.appendChild(el("li",item.reason||item.requirement_id));block.appendChild(list);card.appendChild(block)}
  const details=el("details",undefined,"internal-details"),summary=el("summary","查看完整文件与逐项标准结果");details.appendChild(summary);
  if((delivery.operations||[]).length){details.appendChild(el("div","完整文件变化","trust-subhead"));for(const item of delivery.operations)details.appendChild(el("div",`${item.operation||"change"} · ${item.path||item.previous_path||""}`,"delivery-file"))}
  const stages=state.detail?.delivery_standard?.stages||[];if(stages.length){details.appendChild(el("div","逐项交付标准","trust-subhead"));for(const stage of stages){details.appendChild(el("strong",stage.label));const list=el("ul",undefined,"mini-list");for(const item of [...(stage.baseline_items||[]),...(stage.custom_items||[])])list.appendChild(el("li",`${item.status==="passed"?"已通过":item.status==="failed"?"未通过":"待确认"} · ${item.text}`));details.appendChild(list)}}
  const candidateId=delivery.candidate_id;if(candidateId){const link=el("a","执行与证据详情");link.href=`/api/v1/deliveries/${encodeURIComponent(candidateId)}/evidence`;link.target="_blank";link.rel="noopener";details.appendChild(link)}card.appendChild(details);
  if(delivery.state!=="written"){const actions=el("div",undefined,"delivery-actions"),button=action("接受并写入项目",()=>acceptDelivery(delivery.candidate_id),"primary");button.disabled=!delivery.can_accept;button.setAttribute("aria-describedby",`accept-note-${delivery.candidate_id}`);const note=el("div",delivery.acceptance_effect||"接受前会再次核验并检查冲突。","hint");note.id=`accept-note-${delivery.candidate_id}`;actions.append(button,note);card.appendChild(actions)}
  return card;
}
function renderTrust(){
  const root=document.querySelector("#trust");root.replaceChildren();const detail=state.detail,contract=detail.contracts.at(-1),standard=detail.delivery_standard;
  if(!contract)return;
  const contractSection=el("section",undefined,"trust-section");contractSection.appendChild(el("h2","本次任务与交付标准"));
  contractSection.appendChild(el("div","任务验收","trust-subhead"));contractSection.appendChild(el("p",contract.goal,"trust-copy"));const criteria=el("ul",undefined,"criteria");for(const text of contract.acceptance_criteria||[])criteria.appendChild(el("li",text));contractSection.appendChild(criteria);
  contractSection.appendChild(el("div","交付标准","trust-subhead"));contractSection.appendChild(el("p","说明怎样才算可靠完成。内置基线不可弱化；本次会话标准保存后会生成新契约并重新验证。","trust-copy"));
  const version=el("p",`契约 v${contract.version} · ${contract.workflow}/${contract.profile} · 基线 ${standard?.baseline_version||"sdlc-v1"}`,"hint");contractSection.appendChild(version);const affected=contract.policy?.revision?.affected_stages||[];if(affected.length)contractSection.appendChild(el("p",`本次修订影响：${affected.join("、")}`,"hint"));root.appendChild(contractSection);
  renderCollaboration(root,detail);renderDeliveryStandard(root,standard,contract);
  const internal=el("section",undefined,"trust-section"),details=el("details",undefined,"internal-details"),summary=el("summary","执行与证据详情");details.appendChild(summary);
  details.appendChild(el("div",`Agent 团队 · 最多并行 ${detail.team?.max_parallel||4} · Run ${detail.runs?.length||0} 个`,"trust-subhead"));for(const member of detail.team?.workers||[]){const box=el("div",undefined,`team-member ${member.status||"pending"}`);box.append(el("strong",`${member.role||"Agent"} · ${member.stage_id}`),el("small",`${member.provider||"待分配"} · ${labels[member.status]||member.status}`));details.appendChild(box)}
  details.appendChild(el("div","候选历史","trust-subhead"));for(const item of [...detail.candidates].reverse()){const box=el("div",undefined,"delivery");box.appendChild(el("strong",`候选 v${item.version} · ${labels[item.status]||item.status}`));if(["verified","accepted","failed"].includes(item.status)){const link=el("a","查看 Evidence");link.href=`/api/v1/deliveries/${encodeURIComponent(item.candidate_id)}/evidence`;link.target="_blank";link.rel="noopener";box.appendChild(link)}details.appendChild(box)}internal.appendChild(details);root.appendChild(internal);
};
function renderCollaboration(root,detail){
  if((detail.conversation?.mode||"legacy_pipeline")==="legacy_pipeline")return;
  const section=el("section",undefined,"trust-section"),mode=detail.conversation.mode==="orchestrated"?"编排执行":"直接执行";section.appendChild(el("h2",`${mode} · Conversation 原生协作`));
  const participants=el("div",undefined,"dag");for(const item of detail.participants||[]){const box=el("div",undefined,"dag-node"),head=el("header"),name=el("strong",item.display_name),cap=el("span",item.available?"可用":"不可用",`status-text ${item.available?"passed":"failed"}`);head.append(name,cap);box.append(head,el("small",`${item.agent_id} · ${item.cli_id} · ${(item.capability_tags||[]).join(" / ")}`));participants.appendChild(box)}section.appendChild(participants);
  const plan=(detail.plans||[]).find(item=>item.plan_id===detail.conversation.active_plan_id);if(plan){section.appendChild(el("div",`DAG v${plan.version} · ${labels[plan.status]||plan.status} · 最大并行 ${plan.plan?.max_parallel||4}`,"trust-subhead"));const dag=el("div",undefined,"dag"),byNode=new Map((detail.assignments||[]).filter(item=>item.plan_id===plan.plan_id).map(item=>[item.node_id,item]));for(const node of plan.plan?.nodes||[]){const assignment=byNode.get(node.id)||{},box=el("div",undefined,"dag-node"),head=el("header");head.append(el("strong",node.title),el("span",labels[assignment.status]||assignment.status||"proposed",`status-text ${assignment.status||"pending"}`));box.append(head,el("small",`${node.agent_id} · ${node.work_mode} · 依赖 ${(node.dependencies||[]).join("、")||"无"}`),el("div",node.brief,"card-copy"));dag.appendChild(box)}section.appendChild(dag)}
  section.appendChild(el("div","Assignments 与 Sessions","trust-subhead"));for(const assignment of detail.assignments||[]){const box=el("div",undefined,`team-member ${assignment.status}`);box.append(el("strong",`${assignment.title} · ${assignment.agent_id}`),el("small",`${assignment.assignment_id} · ${assignment.work_mode} · ${labels[assignment.status]||assignment.status}`));section.appendChild(box)}root.appendChild(section);
}
function renderDeliveryStandard(root,standard,contract){
  const section=el("section",undefined,"trust-section"),summary=standard?.summary||{};section.appendChild(el("h2",`交付标准 · ${summary.pre_accept_passed||0}/${summary.pre_accept_total||0} 已通过`));
  for(const stage of standard?.stages||[]){const box=el("details",undefined,"standard-stage");box.open=true;const head=el("summary"),title=el("span",stage.label),status=el("span",stage.status==="passed"?"已通过":stage.status==="failed"?"未通过":"待确认",`status-text ${stage.status}`);head.append(title,status);box.appendChild(head);const three=el("div",undefined,"standard-three");for(const [label,value] of [["交付什么",stage.deliverable],["怎样算完成",stage.completion],["由什么证明",stage.proof]]){const row=el("div");row.append(el("strong",label),el("span",value));three.appendChild(row)}box.appendChild(three);const list=el("ul",undefined,"standard-list");for(const item of [...(stage.baseline_items||[]),...(stage.custom_items||[])]){const row=el("li",undefined,"standard-item"),badge=el("span",item.source==="baseline"?"内置":"本次会话",`badge ${item.source==="baseline"?"builtin":"conversation"}`),text=el("span",item.source==="baseline"?item.text:`交付：${item.deliverable||item.text}；完成：${item.completion||item.text}；证明：${item.proof||item.text}`),stateText=item.status==="passed"?"已通过":item.status==="failed"?"未通过":"待确认",stateNode=el("span",stateText,`status-text ${item.status}`);row.append(badge,text,stateNode);list.appendChild(row)}box.appendChild(list);section.appendChild(box)}
  const add=action("添加本次会话标准",()=>showDeliveryStandardEditor(section,standard,null),"secondary");add.setAttribute("aria-label","添加或修改本次会话交付标准");section.appendChild(add);root.appendChild(section);
}
function showDeliveryStandardEditor(host,standard,selectedStageId){
  if(host.querySelector(".standard-edit-form"))return;const original=(standard.custom_items||[]).map(item=>JSON.parse(JSON.stringify(item))),draft=original.map(item=>({...item,_key:item.id}));let sequence=0;
  const editor=el("div",undefined,"standard-edit-form"),title=el("strong","编辑本次会话标准"),help=el("p","每项都是硬门禁。检查只能选择已经冻结的运行命令；普通聊天不会修改这些规则。","hint"),rows=el("div"),preview=el("div",undefined,"standard-preview"),controls=el("div",undefined,"recovery-actions");editor.append(title,help,rows,preview,controls);host.appendChild(editor);
  const stages=standard.editable_stages||[],checks=standard.available_checks||[];
  function addRule(stageId=selectedStageId){const target=stageId||stages[0]?.stage_id||"";if(draft.filter(item=>item.stage_id===target).length>=10){showNotice("每个阶段最多添加 10 条标准",true);return}draft.push({_key:`new-${++sequence}`,stage_id:target,deliverable:"",completion:"",proof:"",source:"conversation",verifier:{type:"agent_review"},required:true});renderRows()}
  function renderRows(){rows.replaceChildren();for(const item of draft){const row=el("div",undefined,"standard-rule-row"),stageLabel=el("label","影响阶段"),stageSelect=el("select"),verifierLabel=el("label","Verifier"),verifierSelect=el("select"),remove=action("删除此规则",()=>{draft.splice(draft.indexOf(item),1);renderRows()},"quiet");for(const stage of stages){const option=el("option",stage.label);option.value=stage.stage_id;stageSelect.appendChild(option)}stageSelect.value=item.stage_id;stageSelect.addEventListener("change",()=>{item.stage_id=stageSelect.value;renderPreview()});const fields=[];for(const [label,key,placeholder] of [["交付什么","deliverable","例如：向后兼容的公开 API"],["怎样算完成","completion","例如：旧客户端契约测试全部通过"],["由什么证明","proof","例如：冻结检查与独立评审"]]){const fieldLabel=el("label",label),input=el("input");input.value=item[key]||item.text||"";input.maxLength=300;input.placeholder=placeholder;input.addEventListener("input",()=>{item[key]=input.value;renderPreview()});fields.push(fieldLabel,input)}for(const [value,label] of [["agent_review","独立 Agent review"],["artifact","内容寻址 artifact"],["human_acceptance","人工接受"]]){const option=el("option",label);option.value=value;verifierSelect.appendChild(option)}for(const check of checks){const option=el("option",`冻结 Runtime check：${check.label}`);option.value=`runtime_check:${check.command_id}`;verifierSelect.appendChild(option)}const type=item.verifier?.type||"agent_review";verifierSelect.value=["check","runtime_check"].includes(type)?`runtime_check:${item.verifier.command_id}`:(type==="review"?"agent_review":type);verifierSelect.addEventListener("change",()=>{item.verifier=verifierSelect.value.startsWith("runtime_check:")?{type:"runtime_check",command_id:verifierSelect.value.slice(14)}:{type:verifierSelect.value};renderPreview()});row.append(stageLabel,stageSelect,...fields,verifierLabel,verifierSelect,remove);rows.appendChild(row)}renderPreview()}
  function renderPreview(){
    const clean=item=>({id:item.id,stage_id:item.stage_id,deliverable:item.deliverable||item.text,completion:item.completion||item.text,proof:item.proof||item.text,source:item.source,verifier:item.verifier,required:item.required}),before=new Map(original.map(item=>[item.id,item])),after=new Map(draft.filter(item=>item.id).map(item=>[item.id,item])),addedItems=draft.filter(item=>!item.id),deletedIds=[...before.keys()].filter(id=>!after.has(id)),modifiedIds=[...after.keys()].filter(id=>before.has(id)&&JSON.stringify(clean(after.get(id)))!==JSON.stringify(clean(before.get(id)))),affected=[...new Set([...addedItems.map(item=>item.stage_id),...deletedIds.map(id=>before.get(id)?.stage_id),...modifiedIds.flatMap(id=>[before.get(id)?.stage_id,after.get(id)?.stage_id])].filter(Boolean))];
    preview.textContent=`保存预览：新增 ${addedItems.length}，修改 ${modifiedIds.length}，删除 ${deletedIds.length}。受影响阶段：${affected.join("、")||"无"}。保存后生成新契约，当前候选将失效并重新验证。`;
  }
  controls.append(action("添加一条",()=>addRule(),"secondary"),action("保存为新契约",()=>saveDeliveryStandards(draft),"primary"),action("取消",()=>editor.remove(),"quiet"));if(!draft.length)addRule();else renderRows();editor.querySelector("input")?.focus();
}
async function saveDeliveryStandards(items){
  const customItems=items.map(item=>{const value={stage_id:item.stage_id,deliverable:(item.deliverable||item.text||"").trim(),completion:(item.completion||item.text||"").trim(),proof:(item.proof||item.text||"").trim(),source:"conversation",verifier:item.verifier||{type:"agent_review"},required:true};if(item.id)value.id=item.id;if(item.assignment_id)value.assignment_id=item.assignment_id;return value}).filter(item=>item.deliverable&&item.completion&&item.proof);
  try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"revise_contract",payload:{delivery_standard:{custom_items:customItems}},idempotency_key:crypto.randomUUID()})});showNotice("已保存为新契约；旧候选已失效，将按新标准重新验证");setTimeout(refreshDetail,500)}catch(error){showNotice(error.message,true)}
}
async function sendAction(actionName,payload={}){try{await api(`/api/v1/conversations/${encodeURIComponent(state.selected)}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:actionName,payload,idempotency_key:crypto.randomUUID()})});showNotice("操作已提交");setTimeout(refreshDetail,700)}catch(error){showNotice(error.message,true)}}
async function acceptDelivery(candidateId){try{await api(`/api/v2/deliveries/${encodeURIComponent(candidateId)}/accept`,{method:"POST"});showNotice("可信交付已接受并安全写回工作区");await refreshDetail()}catch(error){showNotice(error.message,true)}}
async function approvePlan(planId){try{await api(`/api/v2/conversations/${encodeURIComponent(state.selected)}/orchestration/approve`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan_id:planId})});showNotice("DAG 与分工已冻结，开始并行执行");await refreshDetail()}catch(error){showNotice(error.message,true)}}
async function approveVerification(){try{await api(`/api/v2/conversations/${encodeURIComponent(state.selected)}/verification/approve`,{method:"POST"});showNotice("Strict 验证已确认");await refreshDetail()}catch(error){showNotice(error.message,true)}}
function renderTerminalTabs(){const root=document.querySelector("#terminal-tabs");root.replaceChildren();for(const session of state.detail?.sessions||[]){const button=el("button",`${session.agent_id} · ${session.status}`,`terminal-tab${session.session_id===state.sessionId?" active":""}`);button.type="button";button.addEventListener("click",()=>openTerminal(session.session_id));root.appendChild(button)}}
function openTerminal(sessionId){const drawer=document.querySelector("#terminal-drawer");drawer.classList.remove("hidden");if(state.socket)state.socket.close();if(state.terminal)state.terminal.dispose();state.sessionId=sessionId;state.lease=false;state.terminal=new Terminal({convertEol:false,cursorBlink:true,fontSize:13,theme:{background:"#101828",foreground:"#f2f4f7"},scrollback:5000});state.fit=new FitAddon.FitAddon();state.terminal.loadAddon(state.fit);state.terminal.open(document.querySelector("#terminal-screen"));state.fit.fit();state.terminal.onData(data=>{if(state.lease&&state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:"input",data}));else if(!state.lease)showNotice("当前终端只读，请先点击接管终端",true)});state.terminal.onResize(size=>state.socket?.readyState===WebSocket.OPEN&&state.socket.send(JSON.stringify({type:"resize",cols:size.cols,rows:size.rows})));const scheme=location.protocol==="https:"?"wss":"ws";state.socket=new WebSocket(`${scheme}://${location.host}/api/v2/sessions/${encodeURIComponent(sessionId)}/terminal`);state.socket.addEventListener("open",()=>{state.fit.fit();state.socket.send(JSON.stringify({type:"attach",after_seq:0,cols:state.terminal.cols,rows:state.terminal.rows,request_write:false}))});state.socket.addEventListener("message",event=>{const frame=JSON.parse(event.data);if(frame.type==="output")state.terminal.write(frame.data);else if(frame.type==="lease"){state.lease=Boolean(frame.granted);showNotice(state.lease?"已获得终端写入租约":"终端保持只读")}else if(frame.type==="error")showNotice(frame.message||frame.code||"终端错误",true)});state.socket.addEventListener("close",()=>{state.lease=false});renderTerminalTabs()}
document.querySelector("#terminal-takeover").addEventListener("click",()=>{if(state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:"attach",after_seq:0,cols:state.terminal.cols,rows:state.terminal.rows,request_write:true,takeover:true}))});document.querySelector("#terminal-close").addEventListener("click",()=>document.querySelector("#terminal-drawer").classList.add("hidden"));for(const button of document.querySelectorAll("[data-key]"))button.addEventListener("click",()=>{if(state.lease&&state.socket?.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({type:"input",data:button.dataset.key}))});window.addEventListener("resize",()=>state.fit?.fit());
document.querySelector("#new-toggle").addEventListener("click",()=>document.querySelector("#new-form").classList.remove("hidden"));document.querySelector("#new-cancel").addEventListener("click",()=>document.querySelector("#new-form").classList.add("hidden"));document.querySelector("#new-mode").addEventListener("change",event=>{if(event.target.value==="orchestrated"){const select=document.querySelector("#new-agent"),option=select.selectedOptions[0];if(option?.dataset.orchestrator!=="true"){const candidate=[...select.options].find(item=>item.dataset.orchestrator==="true");if(candidate)select.value=candidate.value}}});document.querySelector("#new-form").addEventListener("submit",async event=>{event.preventDefault();try{const mode=document.querySelector("#new-mode").value,agent=document.querySelector("#new-agent").value,option=document.querySelector("#new-agent").selectedOptions[0];if(mode==="orchestrated"&&option?.dataset.orchestrator!=="true")throw new Error("请选择具备 orchestrate 能力的 Agent");const payload={goal:document.querySelector("#new-goal").value,title:document.querySelector("#new-title").value||null,profile:document.querySelector("#new-profile").value,mode,agent_id:agent,orchestrator_agent_id:mode==="orchestrated"?agent:null,max_parallel:4};const result=await api("/api/v2/conversations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});document.querySelector("#new-form").reset();document.querySelector("#new-form").classList.add("hidden");await loadConversations();await selectConversation(result.conversation.conversation_id)}catch(error){showNotice(error.message,true)}});document.querySelector("#composer").addEventListener("submit",async event=>{event.preventDefault();const textarea=document.querySelector("#message"),intent=document.querySelector("#intent").value,legacy=state.detail?.conversation?.mode==="legacy_pipeline";try{const url=legacy?`/api/v1/conversations/${encodeURIComponent(state.selected)}/messages`:`/api/v2/conversations/${encodeURIComponent(state.selected)}/messages`,payload=legacy?{content:textarea.value,intent:"change",auto_start:true}:{content:textarea.value,dispatch_kind:intent};await api(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});textarea.value="";showNotice("消息已发送");setTimeout(refreshDetail,600)}catch(error){showNotice(error.message,true)}});for(const filter of document.querySelectorAll(".filter"))filter.addEventListener("click",()=>{for(const item of document.querySelectorAll(".filter"))item.classList.remove("active");filter.classList.add("active");state.filter=filter.dataset.filter||"";loadConversations()});loadProviders();loadConversations().catch(error=>showNotice(error.message,true));
document.querySelector("#pair-form").addEventListener("submit",async event=>{event.preventDefault();try{const response=await fetch("/api/v1/auth/pair",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pairing_code:document.querySelector("#pair-code").value,device_label:document.querySelector("#device-label").value})});if(!response.ok)throw new Error("配对码无效或已过期");document.querySelector("#pairing").classList.add("hidden");await loadConversations();showNotice("设备已安全连接")}catch(error){showNotice(error.message,true)}});
</script>
</body>
</html>"""


def conversation_dashboard_html() -> str:
    return _DASHBOARD_HTML


__all__ = ["conversation_dashboard_html"]
